violation_scraper.py
A tool which by scraping Sonarqube instances returns a sorted list of the most commonly found violations.
Will be used both for research purposes (researching what the most common violations are) and for deciding what processor to try and make next (which one that will have the largest impact).
=> Violation scraper

src/main/java/NoSuchElementProcessor.java, src/main/java/TestHelp.java, src/test/java/NoSuchElementProcessorTest.java, src/test/resources/sonatest/src/main/java/NoSuchElement.java
Processor for dealing with sonarqube bug s2272 - "By contract, any implementation of the java.util.Iterator.next() method should throw a NoSuchElementException exception when the iteration has no more elements."
=> No such element processor

tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/CopyFilesAndFoldersOperation.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/NumberToStringConverterTest.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/ProjectLocationSelectionDialog.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/StringToNumberConverter.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/StringToNumberConverterTest.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/StringToNumberParser.diff, tool-comparison/spongebugs/bigDecimalDoubleConstructor/eclipse/StringToNumberParserTestHarness.diff
Compares the changes SpongeBugs did to Eclipse in commit
4fa5728570c2fde4f7bdf3ba374787a070497775
to what my processor would have done to the parent commit
379ecf5a76c8c0a8c765caaa8c37658640bf088f
All changes are semantically identical except for the fact that
SpongeBugs converts non-floating point parameters too.
Changes that were identical are represented by empty files.
=> Comparison of SpongeBugs and SQ-repair for s2111

pull-requests/sling-launchpad-base/4973/Main.diff, pull-requests/sling-launchpad-base/4973/MainDelegate.diff
Link to PR:
https://github.com/apache/sling-org-apache-sling-launchpad-base/pull/6
Sniper mode only added a single whitespace to each line which was removed manually before making the pull request.
=> BoxedTypesEquals PR to Apache Sling Launchpad Base

pull-requests/sling-scripting-jcr/4973/TagFileProcessor.diff, pull-requests/sling-scripting-jcr/4973/XMLEncodingDetector.diff
Link to PR:
https://github.com/apache/sling-org-apache-sling-scripting-jsp/pull/2/files
Sniper mode added single spaces on all lines except one. All were removed manually before making the pull request.
=> BoxedTypesEquals PR to Apache Sling Scripting JSP

pull-requests/sling-scripting-esx/4973/Module.diff
Link to PR:
https://github.com/apache/sling-org-apache-sling-scripting-esx/pull/1/
Sniper mode only added a single whitespace which was removed manually before making the pull request.
=> BoxedTypesEquals PR to Apache Sling Scripting ESX

pull-requests/sling-discovery/4973/VotingView.diff
Normal repair had to be used due to SniperPrettyBug:
spoon.SpoonException: Unexpected state: Token writer is muted after scanning
[Link to PR](https://github.com/apache/sling-org-apache-sling-discovery-impl/pull/1)
[Link to Jira ticket](https://issues.apache.org/jira/browse/SLING-8825)
=> NormalRepair of sling-discovery rule 4973

pull-requests/sling-auth-core/4973/SlingAuthenticator.diff
Link to PR:
https://github.com/apache/sling-org-apache-sling-auth-core/pull/1
Sniper mode only added a single whitespace which was removed manually before making the pull request.
=> BoxedTypesEquals PR to Apache Sling Auth-Core

pull-requests/pdfbox/2272/PDOutlineItemIterator.diff, pull-requests/pdfbox/2272/PDPageTree.diff
Link to PR:
https://github.com/apache/pdfbox/pull/76
https://issues.apache.org/jira/browse/PDFBOX-4687
Had to use normal-mode for one of the files due to it throwing some exception in sniper mode.
The file transformed with sniper mode had to have a newline added before the new statement.
=> NoSuchElementException PR to Apache PDFBox

pull-requests/pdfbox/2111/TilingPaint.diff
Link to PR:
https://github.com/apache/pdfbox/pull/76
Link to Jira:
https://issues.apache.org/jira/browse/PDFBOX-4688
Sniper mode produced a perfect fix.
=> BigDecimalDoubleConstructor PR to PDFBox

src/main/java/Bug.java
This PR intends to fix the errors reported in #45.
=> Fix exceptions being thrown while executing 3 tests.

src/main/java/Main.java, src/main/java/Processors.java, src/main/java/TestHelp.java, src/test/java/ArrayHashCodeAndToStringProcessorTest.java, src/test/java/BigDecimalDoubleConstructorProcessorTest.java, src/test/java/CompareStringsBoxedTypesWithEqualsProcessorTest.java, src/test/java/DeadStoreProcessorTest.java, src/test/java/IteratorNextExceptionProcessorTest.java, src/test/java/SerializableFieldInSerializableClassProcessorTest.java, src/test/java/TestHelper.java, src/test/java/UnclosedResourcesProcessorTest.java
`TestHelp` is a class with major things (such as the core methods) and a minor thing (the method that is actually a test helper). It also contains dead code and it is located in `src/main/java` instead of `src/test/java`. This PR refactors `TestHelp` to make the things much easier to understand. The commit messages in this PR explains nicely what was changed.
=> Refactor TestHelp

src/main/java/sonarquberepair/Main.java, src/main/java/sonarquberepair/Processors.java, src/main/java/sonarquberepair/processor/sonarbased/Bug.java, src/main/java/sonarquberepair/processor/sonarbased/DeadStoreProcessor.java, src/main/java/sonarquberepair/processor/sonarbased/SerializableFieldInSerializableClassProcessor.java, src/main/java/sonarquberepair/processor/sonarbased/SonarWebAPIBasedProcessor.java, src/main/java/sonarquberepair/processor/sonarbased/UnclosedResourcesProcessor.java, src/main/java/sonarquberepair/processor/spoonbased/ArrayHashCodeAndToStringProcessor.java, src/main/java/sonarquberepair/processor/spoonbased/BigDecimalDoubleConstructorProcessor.java, src/main/java/sonarquberepair/processor/spoonbased/CompareStringsBoxedTypesWithEqualsProcessor.java, src/main/java/sonarquberepair/processor/spoonbased/IteratorNextExceptionProcessor.java, src/test/java/sonarquberepair/Constants.java, src/test/java/sonarquberepair/TestHelper.java, src/test/java/sonarquberepair/processor/sonarbased/DeadStoreProcessorTest.java, src/test/java/sonarquberepair/processor/sonarbased/SerializableFieldInSerializableClassProcessorTest.java, src/test/java/sonarquberepair/processor/sonarbased/UnclosedResourcesProcessorTest.java, src/test/java/sonarquberepair/processor/spoonbased/ArrayHashCodeAndToStringProcessorTest.java, src/test/java/sonarquberepair/processor/spoonbased/BigDecimalDoubleConstructorProcessorTest.java, src/test/java/sonarquberepair/processor/spoonbased/CompareStringsBoxedTypesWithEqualsProcessorTest.java, src/test/java/sonarquberepair/processor/spoonbased/IteratorNextExceptionProcessorTest.java, src/test/resources/ArrayHashCodeAndToString.java, src/test/resources/BigDecimalDoubleConstructor.java, src/test/resources/CodeFactory.java, src/test/resources/CompareStringsBoxedTypesWithEquals.java, src/test/resources/IteratorNextException.java
This repository contains a mix of several coding styles across the source code files. This PR fixes that.
=> Change project coding style

src/main/java/sonarquberepair/Processors.java
This PR does a small change to improve `Processors.java`.
=> Improve Processors.java

docs/HANDLED_RULES.md
This PR updates the table of contents in `HANDLED_RULES.md` with the two new rules handled by @henry-lp's processors.
=> Update table of contents in HANDLED_RULES.md

.gitignore, src/main/java/sonarquberepair/DefaultRepair.java, src/test/java/sonarquberepair/FileOutputStrategyTest.java, src/test/java/sonarquberepair/TestHelper.java
This PR improves `DefaultRepair.java`. The commit messages below are helpful to understand the performed changes.
=> Improve DefaultRepair

.travis.yml, pom.xml
=> Fix broken jar

README.md, src/main/java/sonarquberepair/Main.java, src/main/java/sonarquberepair/ProcessorAnnotation.java, src/main/java/sonarquberepair/Processors.java, src/main/java/sonarquberepair/processor/ArrayHashCodeAndToStringProcessor.java, src/main/java/sonarquberepair/processor/BigDecimalDoubleConstructorProcessor.java, src/main/java/sonarquberepair/processor/CastArithmeticOperandProcessor.java, src/main/java/sonarquberepair/processor/CompareStringsBoxedTypesWithEqualsProcessor.java, src/main/java/sonarquberepair/processor/CompareToReturnValueProcessor.java, src/main/java/sonarquberepair/processor/DeadStoreProcessor.java, src/main/java/sonarquberepair/processor/EqualsOnAtomicClassProcessor.java, src/main/java/sonarquberepair/processor/GetClassLoaderProcessor.java, src/main/java/sonarquberepair/processor/IteratorNextExceptionProcessor.java, src/main/java/sonarquberepair/processor/MathOnFloatProcessor.java, src/main/java/sonarquberepair/processor/SelfAssignementProcessor.java, src/main/java/sonarquberepair/processor/SerializableFieldInSerializableClassProcessor.java, src/main/java/sonarquberepair/processor/SynchronizationOnGetClassProcessor.java, src/main/java/sonarquberepair/processor/SynchronizationOnStringOrBoxedProcessor.java, src/main/java/sonarquberepair/processor/UnclosedResourcesProcessor.java, src/main/java/sonarquberepair/processor/UnusedThrowableProcessor.java
Since we added the JSAP args (see https://github.com/SpoonLabs/sonarqube-repair/pull/64), we have not updated the usage of the tool. This PR solves that.
=> Improve usage

README.md, src/main/java/sorald/Constants.java, src/main/java/sorald/DefaultRepair.java, src/main/java/sorald/Main.java, src/main/java/sorald/SoraldConfig.java, src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java, src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.java, src/main/java/sorald/processor/CastArithmeticOperandProcessor.java, src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java, src/main/java/sorald/processor/CompareToReturnValueProcessor.java, src/main/java/sorald/processor/DeadStoreProcessor.java, src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.java, src/main/java/sorald/processor/GetClassLoaderProcessor.java, src/main/java/sorald/processor/IteratorNextExceptionProcessor.java, src/main/java/sorald/processor/MathOnFloatProcessor.java, src/main/java/sorald/processor/SelfAssignementProcessor.java, src/main/java/sorald/processor/SerializableFieldInSerializableClassProcessor.java, src/main/java/sorald/processor/SoraldAbstractProcessor.java, src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.java, src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java, src/main/java/sorald/processor/UnclosedResourcesProcessor.java, src/main/java/sorald/processor/UnusedThrowableProcessor.java, src/test/java/sorald/MaxFixesPerRuleTest.java
This PR enable the user to specify the number of rules to be fixed. 
issue #112
@monperrus , @fermadeiral
=> Fix: add max number of fixes per rule

src/main/java/sorald/SoraldConfig.java, src/test/java/sorald/SoraldConfigTest.java
This PR fixes #110.
@henry-lp WDYT?
=> Fix(config): do not allow that the same processor runs more than once

src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java
This PR fixes #108.
@henry-lp WDYT?
=> Fix(rule-2116): change a detail in the patch creation so that the import of 'java.util.Arrays' is done

src/main/java/sorald/segment/Node.java, src/main/java/sorald/segment/SoraldTreeBuilderAlgorithm.java, src/test/java/sorald/segment/SoraldTreeBuilderAlgorithmTest.java
Related issue: #129
This is a breakdown from this PR #130.
@fermadeiral ready for review.
=> Feat: add tree algorithm for segment mode

src/main/java/sorald/segment/FirstFitSegmentationAlgorithm.java, src/main/java/sorald/segment/Pair.java, src/test/java/sorald/segment/FirstFitSegmentationAlgorithmTest.java
Related issue: #129
This is a breakdown from this PR #130.
@fermadeiral ready for review.
=> Feat: add segmentation algorithm

README.md, src/main/java/sorald/Constants.java, src/main/java/sorald/DefaultRepair.java, src/main/java/sorald/Main.java, src/main/java/sorald/RepairStrategy.java, src/main/java/sorald/SegmentRepair.java, src/main/java/sorald/SoraldAbstractRepair.java, src/main/java/sorald/SoraldConfig.java, src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java, src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.java, src/main/java/sorald/processor/CastArithmeticOperandProcessor.java, src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java, src/main/java/sorald/processor/CompareToReturnValueProcessor.java, src/main/java/sorald/processor/DeadStoreProcessor.java, src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.java, src/main/java/sorald/processor/GetClassLoaderProcessor.java, src/main/java/sorald/processor/InterruptedExceptionProcessor.java, src/main/java/sorald/processor/IteratorNextExceptionProcessor.java, src/main/java/sorald/processor/MathOnFloatProcessor.java, src/main/java/sorald/processor/SelfAssignementProcessor.java, src/main/java/sorald/processor/SerializableFieldInSerializableClassProcessor.java, src/main/java/sorald/processor/SoraldAbstractProcessor.java, src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.java, src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java, src/main/java/sorald/processor/UnclosedResourcesProcessor.java, src/main/java/sorald/processor/UnusedThrowableProcessor.java, src/test/java/sorald/SegmentStrategyTest.java
Related issue: #129
This is a breakdown from this PR #130.
@fermadeiral ready for review.
PS: I need to fix some formatting issues with intellj before merge. It'll be pushed in a new commit.
=> Feat: add sorald segment mode for single rule repair

src/main/java/sorald/processor/SoraldAbstractProcessor.java, src/test/java/sorald/NoSonarTest.java, src/test/resources/NOSONARCommentTest.java
Signed-off-by: henry-lp <tailp@kth.se>
=> Feat: enable NOSONAR comment to ignore warning

pom.xml, src/test/java/sorald/segment/FirstFitSegmentationAlgorithmTest.java, src/test/java/sorald/segment/SoraldTreeBuilderAlgorithmTest.java
Signed-off-by: henry-lp <tailp@kth.se>
Related issue: #138
=> Fix: fix test for deployment

docs/CONTRIBUTING.md
Update of the contributing instructions in regards to the updated tests from #141 / #144 
@fermadeiral This is ready for review, feel free to be picky about contents and phrasing.
=> doc: Update CONTRIBUTING.md with new processor testing

src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java, src/test/resources/processor_test_files/4973_CompareStringsBoxedTypesWithEquals/CompareStringsBoxedTypesWithEquals.java.expected
I was feeling very unproductive, so I decided to do something easy. This PR is a pure refactor, and also adds the expected output of the processor as computed _before_ the refactor. Having the expected output is hugely beneficial when refactoring; I completely broke the processor on my first attempt, which was caught by the computed output not matching the expected output.
=> refactor: Refactor CompareStringsBoxedTypeWithEqualsProcessor

docs/CONTRIBUTING.md
Fix #178 
Feel free to disagree on requiring an expected output file for each test case, I just thought that as the PR should include the diff, they must essentially have the expected out put anyway.
=> doc: Update contributing guidelines

src/main/java/sorald/DefaultRepair.java, src/main/java/sorald/FileUtils.java, src/main/java/sorald/SoraldAbstractRepair.java, src/test/java/sorald/TestHelper.java, src/test/java/sorald/WorkspaceCleaner.java
Pure refactor. Saw the comment in the source code, and as it was a 2-min fix I did it.
=> refactor: Move delete directory method to file utils

src/main/java/sorald/processor/XxeProcessingProcessor.java
Related to #194 
The XxeProcessingProcessor is heavily WIP and should be marked as incomplete.
=> Mark XxeProcessingProcessor as incomplete

docs/CONTRIBUTING.md
Adds a note in `CONTRIBUTING.md` about some issues one may face in building Sorald with an IDE (based on my experience with IntelliJ IDEA). @khaes-kth since you're getting started with Sorald again soon, I think it's important that you read/review this :)
=> doc: Add a note about problems building the project with an IDE

docs/CONTRIBUTING.md
Fix #235 
Just putting our discussion in #235 into writing in the repo. To be discussed during the meeting on the 25th.
=> doc: Update CONTRIBUTING.md with PR guidelines

src/main/java/sorald/Repair.java, src/main/java/sorald/cli/Cli.java, src/main/java/sorald/event/EventType.java, src/main/java/sorald/event/StatisticsCollector.java, src/main/java/sorald/event/StatsMetadataKeys.java, src/main/java/sorald/event/models/RepairEvent.java, src/main/java/sorald/event/models/repair/RuleRepairStatistics.java, src/main/java/sorald/processor/SoraldAbstractProcessor.java, src/test/java/sorald/GatherStatsTest.java
Fix #246 
This turned out to be more work than I thought. The granularity of the data listed in the schema is high, and it was non-trivial to get put it together.
Still working on it, but I'll be done tomorrow morning.
=> feat: Add more output to repair statistics

src/main/java/sorald/Constants.java, src/main/java/sorald/cli/MineCommand.java, src/main/java/sorald/sonar/Checks.java, src/test/java/sorald/miner/WarningMinerTest.java
This PR is going to address #295 .
=> feat: Adds an option to mine only implemented rules

pom.xml
=> chore: Use Spoon 8.4.0-beta-11

.github/workflows/support.yml
Fix #255 
Final piece of the puzzle for #255. To be discussed during the meeting that we're currently in :)
=> chore: Add workflow to generate achievements.md

experimentation/prs.json
This PR adds a record for an opened but not merged/closed PR in verificatum-vmn. I want to see that our tooling handles non-merged PRs.
After this has been merged, a new PR _should_ be opened by the GitHub actions bot with an update to the `ACHIEVEMENTS.md` file.
=> experiment: Add initial record for PR 12 to verificatum-vmn

src/main/java/sorald/Constants.java
=> refactor: Remove unused constant

pom.xml
Fix #362 
Beta 14 was delayed by a lot due to some issues with Spoon's CI (see inria/spoon#3775)
=> chore: Use Spoon 8.4.0-beta-14

experimentation/prs.json
Adds the complete record for spoonlabs/sorald#381 to prs.json.
This includes the initial data, the "manual" edit (autoformatter removed an import statement), and the final data.
**Merge #394 before this one**
=> experiment: Add complete record for spoonlabs/sorald PR 381

experimentation/prs.json
Another PR for Verificatum. This is the initial record (i.e. PR is not yet merged). You can find the PR by looking at the `prMetadata` section of the record.
=> experiment: Add initial record for verificatum/verificatum-vmn PR 13

src/main/java/sorald/Repair.java, src/main/java/sorald/cli/RepairCommand.java, src/main/java/sorald/sonar/ProjectScanner.java
Fix #402 
See a comment for where the actual optimization is at. The rest of the changes are just infrastructure to support that single change.
=> perf: Optimize post-repair violation mining

src/main/java/sorald/Constants.java, src/test/java/sorald/FileOutputStrategyTest.java, src/test/java/sorald/FileUtilsTest.java, src/test/java/sorald/MavenHelper.java, src/test/java/sorald/MavenLauncherTest.java, src/test/java/sorald/MultipleProcessorsTest.java, src/test/java/sorald/SegmentStrategyTest.java, src/test/java/sorald/TargetedRepairTest.java, src/test/java/sorald/cli/CliTest.java, src/test/java/sorald/miner/WarningMinerTest.java, src/test/java/sorald/processor/GreedyBestFitScannerTest.java, src/test/java/sorald/processor/MaxFixesPerRuleTest.java, src/test/java/sorald/processor/NoSonarTest.java, src/test/java/sorald/processor/ProcessorTest.java, src/test/java/sorald/processor/ProcessorTestHelper.java, src/test/java/sorald/segment/FirstFitSegmentationAlgorithmTest.java, src/test/java/sorald/segment/SoraldTreeBuilderAlgorithmTest.java, src/test/java/sorald/sonar/RuleVerifierTest.java, src/test/java/sorald/sonar/RuleViolationTest.java
#166 
First PR to start using Path/File instead of String to represent paths. Title says it all about the changes in this PR.
=> refactor: Make Constants.PATH_TO_RESOURCES_FOLDER an actual Path

src/main/java/sorald/processor/DeadStoreProcessor.java, src/test/resources/processor_test_files/1854_DeadStore/DeadStoreWithInvocation.java, src/test/resources/processor_test_files/1854_DeadStore/DeadStoreWithInvocation.java.expected
Fix #412 
See the issue for a description of the problem. The fix is trivial, see e1c91ca.
=> fix: Fix DeadStoreProcessor deleting invocations

docs/REPOS_REACTIONS.md
Creates REPOS_REACTIONS.md file according to #388 discussions.
=> docs: Create REPOS_REACTIONS.md

src/main/java/sorald/Constants.java, src/main/java/sorald/FileUtils.java, src/main/java/sorald/Repair.java, src/main/java/sorald/SoraldConfig.java, src/main/java/sorald/segment/FirstFitSegmentationAlgorithm.java, src/main/java/sorald/sonar/RuleVerifier.java
This PR just cleans up a bunch of unused methods and fields that I found lying around.
We do have a LOT of warnings on unused methods in the code, but a lot of that is actually used implicitly, e.g. by the JSON output processing. The stuff removed in this PR is however evidently entirely unused.
=> refactor: Remove unused code

experimentation/prs.json
PR was merged a week ago, here's the final record :)
=> doc: Add final record for verificatum/verificatum-vmn PR 13

experimentation/prs.json
Adds complete records for two Spoon PRs (inria/spoon#3852 and inria/spoon#3853)!
=> doc: Add records for Spoon PRs 3852 and 3853

.github/workflows/tests.yml
=> chore: Use setup-java v2.0.0

.github/workflows/deploy.yml
=> chore: Add deploy workflow

.github/workflows/sorald_buildbreaker.yml, src/main/java/sorald/Main.java
Fix #478 
This PR adds the custom Sorald buildbreaker GitHub Action that I'm working on. It's pretty much a GHA-encapsulated version of the scripts in #481. It's very barebones at the moment, but works as a proof-of-concept!
* Here's the current output when it finds repairable violations: https://github.com/SpoonLabs/sorald/runs/2380361750#step:3:89
* Here's what it looks like when there are no violations: https://github.com/SpoonLabs/sorald/runs/2380402480#step:3:48
Note also that, when there are no violations, the action is very quick (11s for Sorald), as SonarJava is very pretty fast. Of course, this will increase a lot for larger projects, but it's still a good indication that this is a feasible thing to integrate into CI pipelines.
Contrast the 18 added lines in this PR, with the …
=> chore: Add buildbreaker action workflow

pom.xml
This PR contains the release commit for sorald-0.2.0 and the iteration commit for sorald-0.2.1-SNAPSHOT.
=> Release sorald-0.2.0

codecov.yml
=> chore: Disable Codecov comments

pom.xml
This PR includes the release and next-iteration commits for Sorald 0.3.0 and 0.3.1, respectively.
=> Release sorald 0.3.0

experimentation/prs.json
~WIP, waiting for merge in Spoon~
Done, ready for merge!
=> experimentation: Add full record for Spoon pr 3972

docs/HANDLED_RULES.md
I accidentally put the wrong hyperlink in #584 . This PR corrects that.
=> fix: modify hyperlink in HANDLED_RULES.md to correctly link list item to its description

.github/submit-pr.sh, .github/workflows/support.yml, experimentation/tools/sorald/handled_rules.py
Fixes #592 
Refactored the `run` instruction into a separate script so that it can be reused for generating `HANDLED_RULES.md`.
=> chore: Integrate generation of HANDLED_RULES.md with CI

src/main/java/sorald/processor/CastArithmeticOperandProcessor.md, src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.md, src/main/java/sorald/processor/MathOnFloatProcessor.md, src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.md
Fixed some typographical and grammatical errors which IntelliJ suggested. Let's see if https://github.com/SpoonLabs/sorald/commit/3d9d34ce1de39ccb89917e8608d036094ead0ccf works!
=> docs: Fix typographical and grammatical errors in few processors' README

renovate.json
=> chore: prevent renovate from updating digests

.github/workflows/deploy.yml, .github/workflows/support.yml, .github/workflows/tests.yml
Reference: https://github.com/SpoonLabs/sorald/issues/643#issuecomment-977204429
These changes will allow renovate to submit PR if there is a new release (major, minor, or patch) for a pinned action.
=> chore: activate renovate for suggesting version updates of actions

README.md
We should really have a python script to generate such things. @slarse you opened an issue for that, as far as I remember. Could you link it?
=> docs: update usage of `repair` command

.github/workflows/support.yml, pom.xml
Reference: https://github.com/SpoonLabs/sorald/pull/684#issuecomment-996869667
I configured generations of docs using picocli `ManPageGenerator` as suggested by @slarse . 
A preview of mine command's usage. ![Screenshot from 2021-12-20 14-53-05](https://user-images.githubusercontent.com/35191225/146777779-c7c2e2ca-0458-4128-96ca-204a69ab05f0.png)
=> chore: automate generation of subcommand usage with picoli

src/main/java/sorald/CodeGenerator.java, src/main/java/sorald/Processors.java, src/main/java/sorald/annotations/ProcessorsClassGenerator.java, src/main/java/sorald/api/ProcessorRepository.java, src/main/java/sorald/cli/RepairCommand.java, src/main/java/sorald/sonar/SonarProcessorRepository.java, src/test/java/sorald/CodeGeneratorTest.java
This PR changes the way processors are loaded to any generic approach.
=> feat: Add processor repository api and sonar implementation

.github/workflows/combine-prs.yml
=> chore: add workflow for combining PRs by renovate

sorald/pom.xml, sorald/src/main/java/sorald/cli/MineCommand.java
The changes ensure that the usage documents stay where they are right now with no change in their content. @MartinWitt, could you please review it?
=> chore: fix `MineCommand` cli documentation

experimentation/tools/sorald/handled_rules.py
=> chore: fix path to processors

sorald/pom.xml, sorald/src/test/resources-its/sorald/it/MineMojoIT/pom_configured/pom.xml
#909 was accidentally squashed and merged. We need to merge all commits separately.
=> chore: prepare release sorald-0.7.0

pom.xml, sorald-api/pom.xml, sorald/pom.xml
Fixes https://github.com/SpoonLabs/sorald/issues/938
=> chore: unpin versions

renovate.json
I won't be able to give much time to this project as I have started with my PhD, but I want the dependencies to be up to date. I will perform occasional releases when I think enough time has passed.
=> chore: enable automerging minor, patch, and pin updates

CITATION.cff
=> doc: add citation file

sorald/src/main/java/sorald/processor/CollectionIsEmptyProcessor.java, sorald/src/main/java/sorald/processor/CollectionIsEmptyProcessor.md, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/ArraysAsList.java, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/ArraysAsList.java.expected, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/FlippedBinaryOperator.java, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/FlippedBinaryOperator.java.expected, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/GreaterThan.java, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/GreaterThan.java.expected, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/LessThan.java, sorald/src/test/resources/processor_test_files/S1155_CollectionIsEmpty/LessThan.java.expected
Fixes #1028 
The exhaustive list is mentioned [here](https://github.com/SonarSource/sonar-java/blob/39f40a17b15ba17f5d9ba1856c3f0187ab605d63/java-checks-test-sources/src/main/java/checks/CollectionIsEmptyCheck.java#L15-L74). I ignored many of them based on heuristics (and laziness), but apparently users want it so here we go :)
=> fix: cover the exhaustive cases in S1155
