src/main/java/TestHelp.java

This needs latest change from Spoon PR https://github.com/INRIA/spoon/pull/1927 too
So now Sniper is really used, but it fails on inconsistent Source position of 
```java
((long) something.getLine())
```
where type cast `(long)` is problem ... https://github.com/INRIA/spoon/issues/2055

fix: create change collector after model is build, but before it's refactoring starts

---

.travis.yml
pom.xml
src/main/java/ArrayToStringProcessor.java
src/main/java/Main.java
src/main/java/NonSerializableSuperClassProcessor.java
src/main/java/NullDereferenceProcessor.java
src/main/java/ParseAPI.java
src/main/java/TestHelp.java
src/test/java/ArrayToStringProcessorTest.java
src/test/java/NonSerializableSuperClassProcessorTest.java
src/test/java/NullDereferenceProcessorTest.java
src/test/java/ResourceCloseProcessorTest.java
src/test/resources/sonatest/src/main/java/ArrayToString.java
src/test/resources/sonatest/src/main/java/NullDereferences.java
src/test/resources/sonatest/src/main/java/SerializableSuperConstructorCheck.java

This PR is mainly a merge of a new processor for SonarQube bug S2116 (https://rules.sonarsource.com/java/type/Bug/RSPEC-2116) of which there is one occurrence in Spoon-Core.
It also disables sniper mode as it is no longer functioning. Seeing as how it was using some imports marked experimental, this isn't too surprising.
It also fixes one of the failing tests (of other processors) but not all. There'll have to be some additional rewriting for those. Namely the NullDereferenceProcessor which doesn't solve its issues with a try-catch block and the NonSerializableSuperClassProcessorTest which doesn't find any issue.

Array to string processor

---

pom.xml
src/main/java/BoxedTypesEqualsProcessor.java
src/main/java/TestHelp.java
src/test/java/BoxedTypesEqualsProcessorTest.java
src/test/resources/sonatest/src/main/java/BoxedTypesEquals.java

Processor for fixing Sonarqube violation S4973, using == instead of .equals() when comparing boxed types.

Boxed equals proocessor

---

pull-requests/sling-feature/4973/Bundles.diff

Link to PR:
https://github.com/apache/sling-org-apache-sling-feature/pull/15
Sniper mode only added a single whitespace which was removed manually before making the pull request.

BoxedTypesEquals PR to Apache Sling Feature

---

src/main/java/TestHelp.java

For testing, we need to insert the comment `// Noncompliant` in lines where there are rule violations (this is mandatory according to Sonar).
We have a method that removes this comment from the source code after Sonarqube-repair repairs it. However, this method only works properly when we have the simple comment `// Noncompliant`, and test cases fail when we have a "bigger" comment like `// Noncompliant {{Cast one of the operands of this addition operation to a "long".}}`. This PR proposes a fix for that.

Fix removal of compliance comments for testing purposes.

---

docs/HANDLED_SONARQUBE_RULES.md

This PR adds a summary (i.e., a table of contents) of handled rules in `docs/HANDLED_SONARQUBE_RULES.md`.

Add a summary of handled rules

---

docs/HANDLED_SONARQUBE_RULES.md
src/main/java/sonarquberepair/processor/sonarbased/Bug.java
src/main/java/sonarquberepair/processor/sonarbased/DeadStoreProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/SerializableFieldInSerializableClassProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/SonarWebAPIBasedProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/UnclosedResourcesProcessor.java
src/test/java/sonarquberepair/processor/sonarbased/SerializableFieldInSerializableClassProcessorTest.java
src/test/java/sonarquberepair/processor/sonarbased/UnclosedResourcesProcessorTest.java

This PR first aimed to simplify the Sonar-Web-API-based processors (and to remove duplicate code and unnecessary code). This was done. But then I found 3 bugs, which were also fixed in this PR.
`DeadStoreProcessor` was removing more things than it should:
Noncompliant code (test code):
```diff
int x=5;
int y=10;
int z;
y=x*x*y;
System.out.println(y);
x=5;// Noncompliant
y=10;// Noncompliant
z=20;// Noncompliant
```
The buggy fix (the repair generated by Sonarqube-repair):
```diff
int x = 5;
int y = 10;
-       int z;
y = (x * x) * y;
System.out.println(y);
-       x=5;// Noncompliant
-       y=10;// Noncompliant
-       z=20;// Noncompliant
```
The correct fix (the repair generated by Sonarqube-repair now with the changes in this PR):
```diff
int x = 5;
int y = 10;
int z;
y = (x * x) * y; …
```

Refactor Sonar-Web-API-based processors

---

docs/HANDLED_SONARQUBE_RULES.md
src/main/java/sonarquberepair/processor/spoonbased/BigDecimalDoubleConstructorProcessor.java
src/test/java/sonarquberepair/processor/spoonbased/BigDecimalDoubleConstructorProcessorTest.java
src/test/resources/ArrayHashCodeAndToString.java
src/test/resources/BigDecimalDoubleConstructor.java
src/test/resources/CompareStringsBoxedTypesWithEquals.java
src/test/resources/IteratorNextException.java

It's important that our processors work well at least on the cases presented by Sonar, the ones that are basic, which can be found in https://rules.sonarsource.com/java and https://github.com/SonarSource/sonar-java/tree/master/java-checks-test-sources. This PR reviews our test resources according to those sources.
After it, I found a bug in `BigDecimalDoubleConstructorProcessor`, which was exposed by new test examples added from Sonar by this PR. The thing is: `BigDecimalDoubleConstructorProcessor` works only on the constructor `BigDecimal(double)`, which failed in the following new test cases:
```java
MathContext mc;
BigDecimal bd4 = new BigDecimal(2.0, mc); // Noncompliant {{Use "BigDecimal.valueOf" instead.}}
BigDecimal bd6 = new BigDecimal(2.0f, mc); // Noncompliant {{Use …
```

Review test resources

---

pom.xml

Soon, we'll deploy a snapshot on Maven Central, if not a release.
We cannot deploy with groupId se.kth
We we can deploy to se.kth.castor, hence this PR.

change groupId to se.kth.castor

---

src/main/java/sonarquberepair/processor/SQRAbstractProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/DeadStoreProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/SerializableFieldInSerializableClassProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/SonarWebAPIBasedProcessor.java
src/main/java/sonarquberepair/processor/sonarbased/UnclosedResourcesProcessor.java
src/main/java/sonarquberepair/processor/spoonbased/ArrayHashCodeAndToStringProcessor.java
src/main/java/sonarquberepair/processor/spoonbased/BigDecimalDoubleConstructorProcessor.java
src/main/java/sonarquberepair/processor/spoonbased/CastArithmeticOperandProcessor.java
src/main/java/sonarquberepair/processor/spoonbased/CompareStringsBoxedTypesWithEqualsProcessor.java
src/main/java/sonarquberepair/processor/spoonbased/IteratorNextExceptionProcessor.java

This PR adds `SQRAbstractProcessor` (SQR = SonarQube-Repair), which extends `spoon.processing.AbstractProcessor`. The motivation for that is that our processors were extending `spoon.processing.AbstractProcessor` directly, without a single, unified super class on sonarqube-repair side for all processors. In this way now, the project is more organized and most important, the same behavior that should be applied to all processors can be implemented only in the super class `SQRAbstractProcessor`, which is the case of the new feature that @henry-lp recently added where the storage of the element being processed is required.

Create SQRAbstractProcessor, which extends spoon.processing.AbstractProcessor

---

README.md
docs/HANDLED_RULES.md
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/processor/spoonbased/MathOnFloatProcessor.java
src/test/java/sonarquberepair/processor/spoonbased/MathOnFloatProcessorTest.java
src/test/resources/MathOnFloat.java

This PR adds a processor for the rule [Math should not be performed on floats](https://rules.sonarsource.com/java/type/Bug/RSPEC-2164).
```diff
// Test for rule s2164
class MathOnFloat {
// Tests from https://github.com/SonarSource/sonar-java/blob/master/java-checks-test-sources/src/main/java/checks/MathOnFloatCheck.java
void myMethod() {
float a = 16777216.0f;
float b = 1.0f;
-        float c = a + b; // Noncompliant {{Use a "double" or "BigDecimal" instead.}} yields 1.6777216E7 not 1.6777217E7
+        float c = (double) a + (double) b; 
-        double d1 = a + b; // Noncompliant ; addition is still between 2 floats
-        double d2 = a - b; // Noncompliant
-        double d3 = a * b; // Noncompliant
-        double d4 = a / b; // Noncompliant
-        double d5 = a / …
```

Add MathOnFloatProcessor (SonarSource rule 2164)

---

README.md
docs/HANDLED_RULES.md
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/processor/spoonbased/EqualsOnAtomicClassProcessor.java
src/test/java/sonarquberepair/processor/spoonbased/EqualsOnAtomicClassProcessorTest.java
src/test/resources/EqualsOnAtomicClass.java

This PR adds a processor for the rule [".equals()" should not be used to test the values of "Atomic" classes](https://rules.sonarsource.com/java/RSPEC-2204).
```diff
// Test for rule s2204
// Tests from https://github.com/SonarSource/sonar-java/blob/master/java-checks-test-sources/src/main/java/checks/EqualsOnAtomicClassCheck.java
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
class EqualsOnAtomicClass {
void method() {
boolean isEqual = false;
AtomicBoolean abool1 = new AtomicBoolean(true);
AtomicBoolean abool2 = new AtomicBoolean(true);
-		isEqual = abool1.equals(abool2); // Noncompliant {{Use ".get()" to retrieve the value and compare it instead.}}
+		isEqual = …
```

Add EqualsOnAtomicClassProcessor (SonarSource rule 2204)

---

README.md
docs/HANDLED_RULES.md
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/processor/spoonbased/SynchronizationOnStringOrBoxedProcessor.java
src/test/java/sonarquberepair/processor/spoonbased/SynchronizationOnStringOrBoxedProcessorTest.java
src/test/resources/SynchronizationOnStringOrBoxed.java

This PR adds a processor for the rule [Synchronization should not be based on Strings or boxed primitives](https://rules.sonarsource.com/java/RSPEC-1860) .
```diff
+  private final Object bLockLegal = new Object();
private final InnerClass i = new InnerClass();
-  void method1() {
-    synchronized(bLock) {}
-    synchronized(i.getLock()){}
-  }
+  void method1() {
+    synchronized(bLockLegal) {}
+    synchronized(i.getLockLegal()){}
+  }
class InnerClass {
public Boolean innerLock = Boolean.FALSE;
+       public Object innerLockLegal = new Object();
public Boolean getLock() {
return this.innerLock;
}
+       public Object getLockLegal() {
+           return this.innerLockLegal;
+       }
}
```

Add SynchronizationOnStringOrBoxedProcessor (SonarRule 1860)

---

README.md
docs/HANDLED_RULES.md
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/processor/spoonbased/SynchronizationOnGetClassProcessor.java
src/test/java/sonarquberepair/processor/spoonbased/SynchronizationOnGetClassProcessorTest.java
src/test/resources/SynchronizationOnGetClass.java

This PR adds a processor for the rule ["getClass" should not be used for synchronization](https://rules.sonarsource.com/java/type/Bug/RSPEC-3067)
```
class SynchronizationOnGetClass {
-  public void method1() {
-    InnerClass i = new InnerClass();
-    synchronized (i.getObject().getClass()) { // Noncompliant - object's modifier is unknown, assume non-final nor enum
-  }
+  public void method1() {
+    InnerClass i = new InnerClass();
+    synchronized(Object.class) {}
+  }
-  public void method2() {
-    synchronized (getClass()) {}
-  }
+  public void method2() {
+    synchronized(SynchronizationOnGetClass.class) {}
+  }
}
```
Regarding enum case (with modifier final), somehow sonarqube failed its own testfile due to nullpointer in their parser. The processor can handle it regardless, …

Add SynchronizationOnGetClassProcessor (SonarRule 3067)

---

README.md
docs/HANDLED_RULES.md
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/processor/UnusedThrowableProcessor.java
src/test/java/sonarquberepair/processor/UnusedThrowableProcessorTest.java
src/test/resources/UnusedThrowable.java

This PR adds a processor for the rule [Exception should not be created without being thrown](https://rules.sonarsource.com/java/RSPEC-3984).
```diff
class UnusedThrowable {
void foo(int x) {
if (x < 0) {
-			new IllegalArgumentException("x must be nonnegative"); // Noncompliant {{Throw this exception or remove this useless statement}}
+			throw new IllegalArgumentException("x must be nonnegative")
+			;
}
if (x < 0) {
throw new IllegalArgumentException("x must be nonnegative");
}
new UnusedThrowable();
Throwable t = new IllegalArgumentException("x must be nonnegative");
if (x < 0) {
throw t;
}
}
}
```
Additional detail: this rule could be also handled by just removing the instantiation of the `Throwable` instead of throwing it.

Add UnusedThrowableProcessor (SonarSource rule 3984)

---

.travis.yml
README.md
init.sh
pom.xml

This PR is the first step for trying to handle the issue #103. Instead of using the changed version of sonar-java by building it locally with
```
git clone --branch modified-version https://github.com/fermadeiral/sonar-java/
cd sonar-java/
mvn install -DskipTests
```
the changes in this PR use a deployed snapshot from https://github.com/fermadeiral/maven-repository

Use deployed sonar-java snapshot

---

README.md
src/main/java/sonarquberepair/DefaultRepair.java
src/main/java/sonarquberepair/Main.java
src/main/java/sonarquberepair/Processors.java
src/main/java/sonarquberepair/SonarQubeRepairConfig.java
src/main/java/sonarquberepair/UniqueTypesCollector.java
src/test/java/sonarquberepair/FileOutputStrategyTest.java
src/test/java/sonarquberepair/MultipleProcessorsTest.java
src/test/resources/MultipleProcessors.java

This PR implements the feature required in #91.
See an example of transformation by 3 different processors, all applied to the same file in a single call to sonarqube-repair:
```diff
- BigDecimal bd2 = new BigDecimal(1.1); // Noncompliant by BigDecimalDoubleConstructorCheck
+ BigDecimal bd2 = BigDecimal.valueOf(1.1); 
- float twoThirds = 2/3; // Noncompliant by CastArithmeticOperandCheck
+ float twoThirds = (float) 2/3; 
AtomicInteger aInt1 = new AtomicInteger(0);
AtomicInteger aInt2 = new AtomicInteger(0);
- isEqual = aInt1.equals(aInt2); // Noncompliant by EqualsOnAtomicClassCheck
+ isEqual = aInt1.get() == aInt2.get(); 
```
The general idea is to receive multiple rule keys as args and, for each rule key, to create a `Launcher` with the processor corresponding to the rule key and run …

Allow multiple rule keys as input

---

docs/MINING_SONAR_WARNINGS.md
src/main/java/sonarquberepair/MineSonarWarnings.java

Hi all,
This is a new, simple feature that we might use for several things, such as checking for projects that might be used in our experiments. More important, this allows us to do large-scale analyses since we don't need to upload projects on Sonar Cloud.
Running the miner on `INRIA/spoon`, passing the folder `/src/main/java/` as argument, for instance, the output will be:
GetClassLoaderCheck=1
SynchronizationOnGetClassCheck=0
CastArithmeticOperandCheck=0
ArrayHashCodeAndToStringCheck=0
UnclosedResourcesCheck=0
BigDecimalDoubleConstructorCheck=0
CompareToReturnValueCheck=0
MathOnFloatCheck=0
UnusedThrowableCheck=0
SynchronizationOnStringOrBoxedCheck=0
SelfAssignementCheck=0
EqualsOnAtomicClassCheck=0
IteratorNextExceptionCheck=0
CompareStringsBoxedTypesWithEqualsCheck=0

Add miner of Sonar warnings

---

src/main/java/sonarquberepair/DefaultRepair.java

A project might have sub projects or files in some resources folder containing classes of the same name as another class in another location. This PR suggests that we ignore loading the same type twice by one-by-one loading in each files into `SpoonLauncher` while skipping the type already occured to improve usability for the CI integration by avoiding `spoon.compiler.ModelBuildingException`. :)
what this PR does:
* Move all buggy files into a new folder in the resources folder
* create a new folder for duplicated files in the resources folder
* Add one-by-one loading logic into `SpoonLauncher`
* Add JSAP option to activate that.
@monperrus @fermadeiral

Feat: skip duplicated types during spoon model building

---

README.md
src/main/java/sorald/Main.java
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/MultipleProcessorsTest.java
src/test/java/sorald/processor/ArrayHashCodeAndToStringProcessorTest.java
src/test/java/sorald/processor/BigDecimalDoubleConstructorProcessorTest.java
src/test/java/sorald/processor/CastArithmeticOperandTest.java
src/test/java/sorald/processor/EqualsOnAtomicClassProcessorTest.java
src/test/java/sorald/processor/GetClassLoaderProcessorTest.java
src/test/java/sorald/processor/MathOnFloatProcessorTest.java
src/test/java/sorald/processor/SelfAssignementProcessorTest.java
src/test/java/sorald/processor/SerializableFieldInSerializableClassProcessorTest.java
src/test/java/sorald/processor/SynchronizationOnGetClassProcessorTest.java
src/test/java/sorald/processor/SynchronizationOnStringOrBoxedProcessorTest.java
src/test/java/sorald/processor/UnclosedResourcesProcessorTest.java
src/test/java/sorald/processor/UnusedThrowableProcessorTest.java

This PR fixes points 1 and 2 in https://github.com/SpoonLabs/sorald/issues/74#issuecomment-639464652.
Note: some test cases do not actually fail with sniper but yet the normal printer is used because the output code is somewhat wrong or with style problems that we might want to report to the Spoon team anyways.

Use sniper printer as the default printer

---

pom.xml

The latest Spoon beta version contains multiple fixes in the sniper printer, thus we should use it.

Update spoon version

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/test/java/sorald/processor/InterruptedExceptionProcessorTest.java
src/test/resources/InterruptedExceptionForTesting.java

This PR adds a processor for the rule ["InterruptedException" should not be ignored](https://rules.sonarsource.com/java/RSPEC-2142).
```diff
+import java.io.IOException;
class InterruptedExceptionForTesting {
static final Log LOGGER;
public void run() {
try {
while (true) {
// do stuff
} 
-		}catch (InterruptedException e) { // Noncompliant; logging is not enough
+        } catch (InterruptedException e) {
+            
LOGGER.log(Level.WARN, "Interrupted!", e);
+            Thread.currentThread().interrupt();
}
}
public void runUnknownSymbol() {
try {
while (true) {
// do stuff
} 
-		}catch (java.io.IOException e) {
+        } catch (IOException e) {
LOGGER.log(Level.WARN, "Interrupted!", e);
-		}catch (InterruptedException e) { // Noncompliant
+        } catch …
```

Add InterruptedExceptionProcessor (SonarSource rule 2142)

---

pom.xml

In preparation for #141, we need JUnit5 for the more powerful parameterized tests. This PR replaces JUnit4 with JUnit5 Jupiter (which is the new engine) and JUnit5 vintage (which allows for running JUnit4 and 3 tests).

Test: Replace JUnit4 with JUnit5 Jupiter + vintage

---

.travis.yml
README.md
pom.xml

This PR adds code coverage with Jacoco and Codecov in preparation for #141. I think it's a good idea to have that seeing as many tests will be migrated to a new format, and it'd be easy to drop one or two by accident.
For everything to work, codecov probably needs to be authorized to the repo. If you'd rather use something else (e.g. coveralls), let me know, I just picked these things because they're what I usually use.

Test: Add code coverage

---

src/main/java/sorald/Constants.java
src/main/java/sorald/miner/MineSonarWarnings.java

#141 
As mentioned in #144, I need a more secure way to load the check classes in the parameterized test. As there already is a large list of checks in `MineSonarWarnings`, I figured I can just extract that and build a lookup table from it. It's not an exhaustive list, but adding a new check to it when we need to is trivial. **This PR just extracts the list of checks to `Constants.java`**, and changes it to contain the classes themselves rather than instances.
I created this separate PR as #144 is becoming so large.
On a side note, the `WarningMinerTest` is dependent on the order of the checks in the list, which tripped me up a bit.

refactor: Extract list of sonar check classes to Constants

---

README.md

This PR adds academic bibliographic references in the README. I realized that this information was missing in our repository because of @slarse's comment [here](https://github.com/SpoonLabs/sorald/issues/82#issuecomment-709903413).
Currently, there is only @HarisAdzemovic's thesis, but soon we will have @henry-lp's thesis and other related scientific works.
@monperrus, WDYT?

Add academic bibliographic references in the README

---

src/main/java/sorald/miner/MineSonarWarnings.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/sonar/Bug.java
src/main/java/sorald/sonar/RuleVerifier.java
src/main/java/sorald/sonar/RuleViolation.java

This is a follow-up on #162, and depends on it. ~**Don't review this until #162 i smerged,** I will fix the commit history.~
This PR extracts the previously internal `SoraldAbstractProcessor.Bug` class into a separate `sorald.sonar.RuleViolation` class, which is just a thin facade around `org.java.sonar.AnalyzerMessage`. Depending on how we proceed with #156, we may not have access to the actual `AnalyzerMessage` (but some higher-level abstraction instead), and so this PR is a precaution.
Since the facade was essentially already there in form of the Bug class, this change was very little effort, and also coincidentally cleans up some of the code base. With this change, the only sonar internals we touch in sorald are the check classes, but it doesn't seem reasonable at the moment to put …

refactor: Add facade around AnalyzerMessage

---

pom.xml
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/MaxFixesPerRuleTest.java
src/test/java/sorald/MultipleProcessorsTest.java
src/test/java/sorald/NoSonarTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/SoraldConfigTest.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/java/sorald/segment/FirstFitSegmentationAlgorithmTest.java
src/test/java/sorald/segment/SoraldTreeBuilderAlgorithmTest.java

Fix #155 
This PR fully adopts JUnit5 by converting all remaining JUnit4 tests. We no longer need the vintage engine, so that's dropped from the pom. This will make more elaborate test fixtures (e.g. the stuff discussed in #153) easier to manage.
The entire conversion was automatic, with the exception of editing the pom and a single test case that had to be slightly rewritten (see review comment).

test: Convert all JUnit4 tests to JUnit5

---

pom.xml
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/WorkspaceCleaner.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener

Fix #153 
This PR introduces a test listener that automatically cleans up the default workspace _before_ each test. It is therefore now safe to use the default workspace for all tests, and all tests that previously interfered with each other now don't.
The listener in question is located in `src/test/sorald/WorkspaceCleaner.java`, and is registered as a test service in `src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener`.

test: Automatically clean default workspace before each test

---

src/main/java/sorald/miner/MineSonarWarnings.java
src/main/java/sorald/sonar/RuleVerifier.java
src/main/java/sorald/sonar/RuleViolation.java
src/test/java/sorald/miner/WarningMinerTest.java

Fix #168 
This PR will conflict with #156 , that one must be merged first.
Optimizes the warnings miner by running all checks in one pass, instead of running one check at a time. Makes the miner many times faster than it was previously.

refactor: Run all checks in one pass in warnings miner

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/PublicStaticFieldShouldBeFinalProcessor.java
src/main/java/sorald/sonar/Checks.java
src/test/resources/processor_test_files/1444_PublicStaticFieldShouldBeFinal/NonFinalPublicStaticField.java
src/test/resources/processor_test_files/1444_PublicStaticFieldShouldBeFinal/NonFinalPublicStaticField.java.expected

This PR adds a processor for the rule ["public static" fields should be constant](https://rules.sonarsource.com/java/RSPEC-1444).
```diff
public class NonFinalPublicStaticField {
-    public static Integer meaningOfLife = 42;
+    public static final Integer meaningOfLife = 42;
private static Integer CATCH = 22; // Compliant
protected static Integer order = 66; // Compliant
static Integer roadToHill = 30; // Compliant
}
```
I did this mostly to test our contributing guidelines, and found some flaws as documented in #178.
There are two things to note about rule 1444 and this new processor.
1. It's categorized as a code smell, but also appears as a vulnerability and so aligns with our prioritization in #51 
- [Example in …

feat: Add PublicStaticFieldShouldBeFinalProcessor (SonarSource rule 1444)

---

src/main/java/sorald/sonar/Checks.java

Adds the selection of vulnerability checks listed in #51, except for a few ones that I couldn't find (deprecated or removed). They must be added in order for me to be able to scan for them with the warnings miner.

feat: Add selection of vulnerability checks

---

src/main/java/sorald/miner/MineSonarWarnings.java
src/main/java/sorald/sonar/RuleVerifier.java
src/test/java/sorald/miner/WarningMinerTest.java

Fix #183 
Fix #184 
This PR does two things.
1. Expose check crashes by not catching all exceptions in the warnings miner
- If there is a crash, we want to know about it, especially when the crash is our fault
2. Fix such a crash in WeakSSLContextCheck by setting the Java version number in the VisitorsBridge to 14
Setting the Java version to 14 is an imperfect fix. It could theoretically cause false positives if a project uses a lesser version of Java by suggesting fixes that aren't applicable to it. Most of these seem related to `< java 8`, though. But setting it too low might cause parsing issues as the parser expects a certain compliance level. As such, I think setting the version a bit too high is preferable to a bit too low at the moment.

fix: Fix handling of crashing checks

---

src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java
src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.java
src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java
src/main/java/sorald/processor/CompareToReturnValueProcessor.java
src/main/java/sorald/processor/DeadStoreProcessor.java
src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.java
src/main/java/sorald/processor/GetClassLoaderProcessor.java
src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/main/java/sorald/processor/IteratorNextExceptionProcessor.java
src/main/java/sorald/processor/MathOnFloatProcessor.java
src/main/java/sorald/processor/PublicStaticFieldShouldBeFinalProcessor.java
src/main/java/sorald/processor/SelfAssignementProcessor.java
src/main/java/sorald/processor/SerializableFieldInSerializableClassProcessor.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.java
src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java
src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/main/java/sorald/processor/UnusedThrowableProcessor.java
src/main/java/sorald/sonar/Checks.java

Fix #177 
This replaces the abstract method `SoraldAbstractProcessor.getSonarCheck` with the `Checks.getCheckInstance` method. As we have all checks in key-to-check mappings, and each processor has an annotation with the key for the rule, this should be a fully sufficient replacement.
The benefit is that new processors don't have to implement the `getSonarCheck` method and, in fact, don't need to know about sonar at all anymore as the abstract base class handles that.

refactor: Replace SoraldAbstractProcessor.getSonarCheck with Checks.getCheckInstance

---

README.md
src/main/java/sorald/Processors.java
src/main/java/sorald/processor/PublicStaticFieldShouldBeFinalProcessor.java
src/main/java/sorald/sonar/IncompleteProcessor.java

Fix #189 
As explained in #189, many processors will be incomplete fixes for their associated rules. We need to make this known both to ourselves (for further development), and to users (to avoid misunderstandings). This PR adds the `IncompleteProcessor` annotation, which can be applied like so.
```java
@IncompleteProcessor(description = "does not fix variable naming")
@ProcessorAnnotation(key = 1444, description = "\"public static\" fields should be constant")
public class PublicStaticFieldShouldBeFinalProcessor extends SoraldAbstractProcessor<CtField<?>> {
```
The description is then added to the `--help` message in the CLI.
```bash
Arguments: 
[--ruleKeys ruleKeys1,ruleKeys2,...,ruleKeysN ]
Choose one or more of the following rule keys (use ',' to separate
multiple keys):
2272: …
```

feat: Add IncompleteProcessor annotation

---

src/main/java/sorald/FileUtils.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/test/java/sorald/FileUtilsTest.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

Fix #204 
This fixes a crash that occurs when you apply Sorald to a project that has a directory ending in `.java`.
This also applies to the miner, but I'll fix that separately.

fix: Avoid processing directories with .java extension as files

---

README.md
docs/CONTRIBUTING.md
pom.xml

Fix #211 
We're dropping support for Java 8 and now only support Java 11+. This PR updates the pom and related documentation.

chore: Switch to Java 11

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/XxeProcessingProcessor.java
src/test/resources/processor_test_files/2755_XxeProcessing/InsecureXMLInputFactoryUsage.java
src/test/resources/processor_test_files/2755_XxeProcessing/InsecureXMLInputFactoryUsage.java.expected

Working toward #194 
This PR adds support for the `XMLInputFactory` in the `XxeProcessingProcessor` which handles the rule [XML parsers should not be vulnerable to XXE attacks](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2755).
The transformation is identical to the one in #201, with the one exception that the setter method is called `setProperty` instead of `setAttribute`.

feat: Add support for XMLInputFactory in XxeProcessingProcessor

---

src/main/java/sorald/miner/MineSonarWarnings.java
src/test/java/sorald/miner/WarningMinerTest.java

Fix #207 
~Depends on #212~
This fixes a crash where the sonar miner would try to read directories that end in `.java` as files. This is essentially the same fix as in #206

fix: Avoid mining directory with Java extension as file

---

codecov.yml

Fix #227 
This is based on the [default Codecov yaml](https://docs.codecov.io/docs/codecov-yaml#default-yaml), with the only difference being:
```
status:
project: off
```

chore: Disable Codecov's project check

---

src/test/java/sorald/MultipleProcessorsTest.java

Fix #170 
Parameterizes the multi-rule test such that it tries to repair multiple rules with both repair strategies. Currently, that means that it tests both the default and the segment strategy, whereas before it only tested the default strategy.
I've tried this test case in relation to the merge of #220 , and it fails before and passes after. So, that redesign fixed the problem.

test: Parameterize multi-rule test case for all repair strategies

---

experimentation/tools/issue_finder/README.md
experimentation/tools/issue_finder/main.py
experimentation/tools/issue_finder/requirements.txt

Fix #231 
This PR adds a script that's just a thin wrapper around GitHub's search API. See the added README for usage.

experiment: Add GitHub issue search script

---

pom.xml

We need a fix I introduced in beta-5 (inria/spoon#3702) to do the PR for RSP server (see #226)

chore: Bump Spoon version to 8.4.0-beta-5

---

src/main/java/sorald/processor/XxeProcessingProcessor.java
src/test/resources/processor_test_files/2755_XxeProcessing/SetFeatureSecureProcessing.java
src/test/resources/processor_test_files/2755_XxeProcessing/SetFeatureSecureProcessing.java.expected

Fix #234 
This PR removes the feature introduced by #219, which was found to be entirely broken (see #234). Unfortunately, #219 wasn't squashed, so simply reverting it was inconvenient.
We will probably want to revisit the topic of checked exceptions later, but I don't think it's a priority until we find the need to work with checked exceptions in multiple processors.

fix(rule 2755): Remove handling of setting of FEATURE_SECURE_PROCESSING

---

src/main/java/sorald/Repair.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/sonar/ProjectScanner.java

This is step 1 of the targeted repair implementation (#225).
This refactor extracts the discovery of rule violations from the SoraldAbstractRepair class and pulls it up to an earlier level of the execution. It makes it much easier to replace the rule violations with something constructed from violation IDs for the targeted repair. See further comments in the code.

refactor: Extract discovery of rule violations from SoraldAbstractRepair

---

src/main/java/sorald/FileUtils.java

To silence this annoying warning when compiling:
```
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/slarse/Documents/github/work/sorald/src/main/java/sorald/FileUtils.java:73: warning: no @throws for java.io.IOException
[WARNING] public static List<File> findFilesByExtension(File directory, String ext) throws IOException {
[WARNING] ^
```

doc: Add throws to findFilesByExtension Javadoc

---

src/main/java/sorald/Repair.java

This is a workaround to #251 
I think as a permanent fix, we should remove the global state of `UniqueTypesCollector`. Global mutable state is a code smell.

fix: Move reset of UniqueTypesCollector to the start of repair

---

README.md
src/main/java/sorald/FileOutputStrategy.java
src/main/java/sorald/Repair.java
src/main/java/sorald/cli/Cli.java
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

Fix #190 
This PR adds an in-place repair mode, which writes output directly to the source files. It's literally in-place; if Sorald processes multiple rules the source files will be written to multiple times.
Can be activated by passing `--fileOutputStrategy IN_PLACE` to the `repair` command.

feat: Add in-place repair mode

---

src/main/java/sorald/Constants.java
src/main/java/sorald/cli/Cli.java
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/MaxFixesPerRuleTest.java
src/test/java/sorald/MultipleProcessorsTest.java
src/test/java/sorald/NoSonarTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

Fix #242 
This is a simple refactor that removes the `Constants.ARG_SYMBOL` constant and puts `--` directly in each argument name. The split was necessary when using the old CLI library, as it required the argument names _without_ the `--` prefix to extract options. picocli doesn't, and so the split is purely an annoyance when writing tests.

refactor: Remove Constants.ARG_SYMBOL

---

src/test/java/sorald/miner/WarningMinerTest.java

Fix #264 
The output from sonar appears to be flaky, so this PR adjusts a test that relied on sonar output to only rely on Sorald's output.

test: Remove reliance on flaky output in miner test

---

src/main/java/sorald/FileUtils.java
src/main/java/sorald/cli/Cli.java

Related to the comments in #269 
@khaes-kth what do you think about this `writeJSON` method? It's completely agnostic about the objects that are passed to it, it will simply use the `coreObj` as a basis for the output, and then attach the key/value pairs of `additionalData` to that output.

refactor: Generalize the writing of JSON output

---

src/main/java/sorald/Main.java
src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/SystemExitHandler.java
src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener

The `Main.main` method currently throws an `IllegalStateException` when there's an error in executing a command. That's super strange, and it looks very odd to a user to see `IllegalStateException` written out in red letters when they mistype a CLI option, or something like that.
This PR fixes that by instead simply exiting non-zero. To make this behavior testable, it adds a custom security manager that throws a particular exception on non-zero exits. The security manager is registered before each test is executed, and unregistered after each test.

fix: Make main method exit non-zero instead of throwing

---

pom.xml
src/test/java/sorald/processor/ProcessorTest.java

Fix #256 
The latest snapshot build of Spoon works for resolving the problem with incorrect indentation. I suggest we simply use the snapshot build of Spoon (except for when we make a release), as I'm fairly often contributing to Spoon to fix issues in Sorald.

fix: Use Spoon snapshot to fix incorrect indentation style

---

docs/CONTRIBUTING.md
src/main/java/sorald/event/EventType.java
src/main/java/sorald/event/StatisticsCollector.java
src/main/java/sorald/event/models/CrashEvent.java
src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java
src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.java
src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java
src/main/java/sorald/processor/CompareToReturnValueProcessor.java
src/main/java/sorald/processor/DeadStoreProcessor.java
src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.java
src/main/java/sorald/processor/GetClassLoaderProcessor.java
src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/main/java/sorald/processor/IteratorNextExceptionProcessor.java
src/main/java/sorald/processor/MathOnFloatProcessor.java
src/main/java/sorald/processor/PublicStaticFieldShouldBeFinalProcessor.java
src/main/java/sorald/processor/SelfAssignementProcessor.java
src/main/java/sorald/processor/SerializableFieldInSerializableClassProcessor.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.java
src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java
src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/main/java/sorald/processor/UnusedThrowableProcessor.java
src/main/java/sorald/processor/XxeProcessingProcessor.java
src/main/java/sorald/sonar/GreedyBestFitScanner.java
src/test/java/sorald/processor/SoraldAbstractProcessorTest.java

Fix #210 
Fix #278 
This PR makes Sorald more resilient to crashes in processor implementations. It essentially does these three things:
* Rename `canRepair` to `canRepairInternal` and create a new concrete method `canRepair` in `SoraldAbstractProcessor` that just calls the internal method and catches any exceptions.
* Same thing for `SoraldAbstractProcessor::repair`
* Wrap the entirety of `SoraldAbstractProcessor::process` in a try/catch.
All these crashes are recorded as crash events, that when printed in the JSON output look something like this:
```json
"crashes": [{
"description": "Crash in sorald.processor.SoraldAbstractProcessorTest.CrashyProcessor::canRepair",
"stackTrace": "java.lang.RuntimeException: I'm a crash :)\n\tat …
```

feat: Make Sorald resilient to crashes in processor implementations

---

pom.xml
src/main/java/sorald/Constants.java
src/main/java/sorald/cli/Cli.java
src/main/java/sorald/cli/SoraldVersionProvider.java
src/test/java/sorald/cli/CliTest.java
src/test/java/sorald/cli/SoraldVersionProviderTest.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/resources/META-INF/bogus-manifests/MANIFEST-RELEASE-VERSION.MF
src/test/resources/META-INF/bogus-manifests/MANIFEST-SNAPSHOT-VERSION.MF
src/test/resources/META-INF/bogus-manifests/MANIFEST-WITHOUT-VERSION.MF

Related to #246 
This PR adds dynamic resolution of version info. The version number is only used if it is a release version (i.e. non-snapshot). Otherwise, falls back on the commit hash (shortened to 8 characters for readability and prefixed with `commit: ` to make it clear that it's a commit hash).
The version and commit hash are added to the MANIFEST.MF file in the jar, which is configured in `pom.xml`
What's also new here is that `sorald --version` now prints the version number, which it did not previously.

feat: Automatically resolve version info

---

src/main/java/sorald/event/StatsMetadataKeys.java
src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java
src/test/resources/processor_test_files/2116_ArrayHashCodeAndToString/UnresolvableType.java

Fix #276 
This PR does three things.
1. 9451185 Adds a check in the `ProcessorTest.testProcessSingleFile` that the statistics collector does not report any crashes
- This is necessary, as the crash reported in #276 is now caught and reported, instead of causing an application failure
2. 8ee678c Adds a new test case file to replicate the problem from #276 
3. 5be0956 Fixes the problem

fix: Fix null dereference in ArrayHashCodeAndToStringProcessor

---

src/main/java/sorald/Repair.java
src/main/java/sorald/cli/RepairCommand.java
src/test/java/sorald/GatherStatsTest.java

Fix #289 
This PR introduces stats collection for segment mode. As there are so few differences between segment mode and default mode, this is fairly trivial. It's just a matter of collecting the running times for parsing and repairing slightly differently.

feat: Enable stats collection in segment mode

---

README.md

This PR updates the usage instructions with options on the form `--some-option` as opposed to the no longer used form `--someOption`. We forgot to do that when updating the CLI.

doc: Update README with new style of options

---

src/main/java/sorald/processor/ArrayHashCodeAndToStringProcessor.java
src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.java
src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java
src/main/java/sorald/processor/CompareToReturnValueProcessor.java
src/main/java/sorald/processor/DeadStoreProcessor.java
src/main/java/sorald/processor/EqualsOnAtomicClassProcessor.java
src/main/java/sorald/processor/GetClassLoaderProcessor.java
src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/main/java/sorald/processor/IteratorNextExceptionProcessor.java
src/main/java/sorald/processor/MathOnFloatProcessor.java
src/main/java/sorald/processor/PublicStaticFieldShouldBeFinalProcessor.java
src/main/java/sorald/processor/SelfAssignementProcessor.java
src/main/java/sorald/processor/SerializableFieldInSerializableClassProcessor.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/processor/SynchronizationOnGetClassProcessor.java
src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java
src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/main/java/sorald/processor/UnusedThrowableProcessor.java
src/main/java/sorald/processor/XxeProcessingProcessor.java

This PR makes all implementations of `repairInternal` and `canRepairInternal` protected (as they should be as they are protected in `SoraldAbstractProcessor`) to demonstrate that it doesn't actually work (833b84d). That is to say, if you implement `SoraldAbstractProcessor` with `protected` `repairInternal` and `canRepairInternal`, the processor won't work.
The problem is fixed in 50a8673 by using `Class.getDeclaredMethods()` (which finds all declared methods) instead of `Class.getMethods()` (which finds all public methods).

fix: Fix detection of protected repairInternal

---

.github/workflows/tests.yml
experimentation/tools/pr_recorder/prrecorder.py
experimentation/tools/pr_recorder/requirements.txt
experimentation/tools/pr_recorder/resources/prs_final.json
experimentation/tools/pr_recorder/resources/prs_initial.json
experimentation/tools/pr_recorder/resources/stats.json
experimentation/tools/pr_recorder/test_prrecorder.py

Fix #265 
@fermadeiral This is my suggestion for recording PRs. Could you have a look at the data in the file, and the general approach? So, this is ready for review ~of the usage and data, but I also want to add some basic tests for this so it's not quite ready to merge.~
Here's an example use case for this PR, based on the PR we made to rsp-server. The script has the following CLI:
```
$ python prrecorder.py --help
usage: prrecorder.py [-h] {record-initial,record-final,add-manual-edit} ...
positional arguments:
{record-initial,record-final,add-manual-edit}
record-initial      make the initial record for a PR
record-final        make the final record for a PR
add-manual-edit     add a diff representing a manual edit of a PR
optional arguments:
-h, --help            show this help message …
```

experiment: Add script for recording Sorald PRs

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/ThreadRunProcessor.java
src/test/resources/processor_test_files/1217_ThreadRun/ThreadRunInvocation.java
src/test/resources/processor_test_files/1217_ThreadRun/ThreadRunInvocation.java.expected

This processes [1217](https://rules.sonarsource.com/java/RSPEC-1217) warnings.

feat(rule 1217): "Thread.run()" should not be called directly

---

pom.xml

Fix #306 
This both makes builds reproducible, and allows us to download the Spoon source code in e.g. IntelliJ IDEA.

chore: Pin Spoon version to 8.4.0-beta-9

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/ToStringReturningNullProcessor.java
src/test/resources/processor_test_files/2225_ToStringReturningNull/NullReturningToString.java
src/test/resources/processor_test_files/2225_ToStringReturningNull/NullReturningToString.java.expected

It's an incomplete processor for [rule 2225](https://rules.sonarsource.com/java/RSPEC-2225). It only handles null-returning `toString()` and not `clone()`.

feat(rule 2225): Null-returning "toString()" functions should return empty string

---

src/main/java/sorald/event/models/miner/MinedViolationEvent.java
src/main/java/sorald/sonar/GreedyBestFitScanner.java

There are three Javadoc warnings when packaging the project:
```
[WARNING] Javadoc Warnings
[WARNING] /home/slarse/Documents/github/work/sorald/src/main/java/sorald/event/models/miner/MinedViolationEvent.java:16: warning: no @param for violation
[WARNING] public MinedViolationEvent(RuleViolation violation, Path projectPath) {
[WARNING] ^
[WARNING] /home/slarse/Documents/github/work/sorald/src/main/java/sorald/event/models/miner/MinedViolationEvent.java:16: warning: no @param for projectPath
[WARNING] public MinedViolationEvent(RuleViolation violation, Path projectPath) {
[WARNING] ^
[WARNING] /home/slarse/Documents/github/work/sorald/src/main/java/sorald/sonar/GreedyBestFitScanner.java:44: warning: no @param for <E>
[WARNING] public static <E extends CtElement> Map<CtElement, …
```

doc: Fix javadoc warnings

---

.github/workflows/tests.yml

Fix #274 
Codecov needs a fetch depth > 1 to be able to identify the commit. Now we should see the PR statuses being posted again.

chore: Set fetch-depth to 2 to allow Codecov to find the commit

---

src/main/java/sorald/sonar/RuleVerifier.java
src/main/java/sorald/sonar/ScannedViolation.java
src/test/java/sorald/sonar/RuleVerifierTest.java
src/test/java/sorald/sonar/ScannedViolationTest.java

Fix #314 
Hardens violation scanning against NPEs by filtering out any `AnalyzerMessage`s that don't have primary locations. If one were to somehow slip through anyway, `ScannedViolation` is now adapted to provide better error messages.

fix: Harden violation scanning against NullPointerException

---

src/main/java/sorald/sonar/RuleVerifier.java
src/test/java/sorald/NoSonarTest.java
src/test/java/sorald/TestHelper.java
src/test/java/sorald/sonar/RuleVerifierTest.java

Fix #316 
Re-implements feature for respecting `// NOSONAR` comments in the source code. The test to check this functionality has also been fixed, and a new one added.

feat: Respect NOSONAR comments

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/LiteralIntOperand.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/LiteralIntOperand.java.expected
src/test/resources/processor_test_files/2184_CastArithmeticOperand/VariableIntOperand.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/VariableIntOperand.java.expected

Fix #321 
This PR changes `CastArithmeticOperandProcessor`'s transformations to use literal suffixes instead of casts when applicable. Here's an example:
```java
// original statement
long val = 1000 * someIntValue;
// old transformation
long val = (long) 1000 * someIntValue;
// new transformation
long val = 1000L * someIntValue;
```
Casts are still used where literal suffixes aren't applicable.
@fermadeiral WDYT, should we make this the default? I personally prefer literal suffixes, but as you noted in #321 none of the transformations or poor from an idiomatic standpoint. We could also hold off until we have the ability to supply options to processors.

feat: Use literal suffixes for CastArithmeticOperandProcessor when applicable

---

.github/workflows/tests.yml
docs/CONTRIBUTING.md
pom.xml
src/main/java/sorald/CodeGenerator.java
src/main/java/sorald/GenerateCode.java
src/main/java/sorald/Processors.java
src/main/java/sorald/annotations/ProcessorsClassGenerator.java
src/test/java/sorald/CodeGeneratorTest.java

Fix #294 
This PR redesigns the code generation such that we commit the code to the repository, instead of relying on annotation processing during compile time. While annotation processing at compile time works great for Maven, I've found that it's in general very tricky to get various IDEs and editors to recognize the generated code as part of the code base. We've only gotten it to work somewhat well with IntelliJ IDEA so far.
So, this PR is meant to make Sorald development friendlier for more development environments. There's one unfortunate side effect, and that is that adding a new processor requires one to manually run the code generation. This isn't hard, but it is an extra step. It's described in CONTRIBUTING.md. There's also a new GitHub Actions job that checks that the generated …

refactor: Commit generated code instead of generating on compile

---

src/main/java/sorald/CompilationUnitHelpers.java
src/main/java/sorald/OutputPaths.java
src/main/java/sorald/Repair.java
src/main/java/sorald/UniqueTypesCollector.java
src/test/java/sorald/processor/ProcessorTestHelper.java
src/test/resources/processor_test_files/1948_SerializableFieldInSerializableClass/SerializableFieldProcessorTest.java.expected

Fix #333 
Fixes the bug in Sorald described in #333, which solves the problem for us. The related bug in Spoon that's mentioned is not a problem for us, although I'll fix that too eventually. Here's the gist of the bug in Sorald:
> In Sorald, we only print top-level types that have been edited. This means that a CU with multiple top-level types may be printed with fewer types than it should, if any of the top-level types have not been edited. This bug is severe, as even when running with the default printer, there are types missing from the output. This also shows the dire need for expected output files for all test cases.
This PR changes the printing logic to work on compilation units instead of individual types. This both fixes the crash in the sniper printer, and the incorrect output …

fix: Fix printing of compilation units with multiple top-level types

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java

This is a tiny refactor. The cast that's changed here casted a boxed value (i.e. an object) directly to int, which _works_, but IDEA flags it as an error. It's technically not an error, but it's a bit of bad practice as technically the cast is to `Integer` and then it auto-unboxes to `int`. The value is also immediately boxed again, so it's pointless.

refactor: Cast boxed type to Integer instead of directly to int

---

pom.xml
src/main/java/sorald/sonar/RuleVerifier.java

Fix #330 
At long last, a fix for this very annoying problem. To summarize #330, the problem is that the `javax.xml` package is both defined in a module in the standard library, _and_ in the `xml-apis` bundle in an unnamed module (i.e. pre java 9 style). This is technically not allowed, a package can only appear in one module, and so _most_ dev environments scream bloody murder. It also causes problems at runtime as JDT has trouble resolving references to `javax.xml.*` classes.
The problem appears to be with version 1.4.01 of xml-apis in particular, whereas 2.0.2 appears to work fine. Strangely enough, 1.4.01 (released in 2011) appears to be much newer than 2.0.2 (released in 2005). I'm not quite sure what's going on there.
Now, we can exclude this dependency from `java-checks-testkit` …

fix: completely exclude xml-apis dependency from project

---

.github/workflows/support.yml

I thought that `expr1 || expr2 && expr3` would implicitly be `expr1 || (expr2 && expr3)` as `&&` typically binds "harder" than `||`. That's apparently not the case in bash :D

chore: Add missing parenthesis in support workflow

---

.github/workflows/support.yml

Fixes a problem where the support workflow would create a branch on each commit, even if `ACHIEVEMENTS.md` did not need updating.

chore: Fix support workflow creating redundant branches

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/CastArithmeticOperand.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/MultipleBinaryOperatorsInMethodCall.java

This PR addresses #125 partially.
The thing is: when the arithmetic operation is inside a method call, and an inner binary operator of the arithmetic operation is being analyzed, we don't find it in the list of arguments of the method call, because that binary operator is part of something more. Not finding it in the list of arguments causes an `IndexOutOfBoundsException` because we have index `-1`. This PR fixes that. Note that such a case was added in the test, which triggers the exception if the patch added in this PR does not exist.

fix: fix an IndexOutOfBoundsException in CastArithmeticOperandProcessor

---

experimentation/tools/sorald/_helpers/jsonkeys.py
experimentation/tools/sorald/achievements.py
experimentation/tools/tests/resources/prs_final.json
experimentation/tools/tests/resources/prs_final_with_legacy.json
experimentation/tools/tests/resources/prs_initial.json
experimentation/tools/tests/test_achievements.py

Fix #255 
This PR adds support for the legacy records added to `prs.json` in #364. In addition, to ensure that our newest achievements don't get lost amidst older achievements, the PRs are now sorted in descending order by date created.
Here is a sample of the markdown generated for a legacy record (note that the hyperlink to the PR is intentionally broken to not display a useless notification in that PR):
This PR was opened at 2019-11-05 11:42:48 and merged at 2019-11-05 19:11:09.
This is a legacy PR made before detailed record-keeping, and so we cannot say if any manual edits have been applied.
It provided the following repairs:
* [Rule 4973](https://rules.sonarsource.com/java/RSPEC-4973)
- Number of violations found: 3
- Number of violations repaired: 3

doc: Update ACHIEVEMENTS.md generation script for keeping legacy records

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/NOCOMPILE_NullOperandType.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/NullOperandType.java

This PR partially addresses #125.
The thing is: when we cannot resolve the type of the left or right hand operand in a binary operator, we get a `NullPointerException`. This PR adds a test case that triggers that exception and the fix for it.

fix: fix a NPE in CastArithmeticOperandProcessor

---

src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/main/java/sorald/sonar/GreedyBestFitScanner.java

Fix #346 
Currently, the GreedyBestFitScanner scans the entire model, and invokes `SoraldAbstractProcessor.canRepair` on _all_ elements that have the correct type. This is bad for several reasons:
1. Inefficient, we both scan too much and invoke `canRepair` too often.
2. The vast majority of elements passed to `canRepair` are not close to any violation, or even in the same file. This is an unnecessary source of crashes.
3. It's not clear to implementers of processors exactly what needs to be checked in `canRepair`, as it's invoked all over the place.
This redesign does two things. First, it does not scan type declarations that don't contain any violations. Second, it only passes elements to `canRepair` after verifying that said elements are _very close_ to a considered violation. …

feat: Only invoke SoraldAbstractProcessor.canRepair on elements close to violations

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/test/resources/processor_test_files/2142_InterruptedException/CatchesWithNestedExits.java
src/test/resources/processor_test_files/2142_InterruptedException/CatchesWithNestedExits.java.expected
src/test/resources/processor_test_files/2142_InterruptedException/InterruptedExceptionForTesting.java.expected

Fix #384 
This PR modifies the processor for rule 2142 to place the interrupt as late as possible in the catch block, but before any throw or return statement. See #384 for why this is necessary.

feat(2142): Add thread interrupt before first throw or return

---

src/main/java/sorald/GitPatchGenerator.java

Hi,
This PR fixes 1 violations of [Sonar Rule 1854: 'Unused assignments should be removed'](https://rules.sonarsource.com/java/RSPEC-1854).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 1854](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#unused-assignments-should-be-removed-sonar-rule-1854).
9521a51 was applied with Spotless.

fix: Fix violations of Sonar rule 1854

---

.github/workflows/support.yml

I'm not sure if anyone's noticed, but we have a `GitHub Web Flow` contributor. That's because of this commit: https://github.com/SpoonLabs/sorald/commit/cfc009279b03b63cb2ceca0ad355fcc55dc525fa
Which lists it as a co-author for the ACHIEVEMENTS file update. That's automatically put there because the auto-updater commits with that user.
This PR makes the support workflow commit with the github-actions bot user instead. It will still generate a "co-authored by", but it will be with an alias of the actions bot, which does not count as a contributor.

chore: Use github-actions bot user as committer for ACHIEVEMENTS update

---

docs/CONTRIBUTING.md

Fix #374 
This PR elaborates on the processor testing docs in `CONTRIBUTING.md` to make the whole process more clear, and also document the use of `IGNORE` and `NOCOMPILE` prefixes for test files.

doc: Improve processor testing docs

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java

Fix #379 
There's no test to verify that this is the case, as we currently don't have support for testing literal output in the test suite, but I've verified it manually. I've opened an issue about augmenting the test suite to allow for testing that arbitrary text is present in the output file, see #393.

feat(2184): Use upper case letter for literal suffixes

---

pom.xml

Just bumps the Spoon version to the latest beta. This PR literally changes one digit, so I'll merge it myself as soon as it passes CI.

chore: Bump Spoon version to 8.4.0-beta-15

---

src/main/java/sorald/cli/RepairCommand.java
src/main/java/sorald/cli/SpecifiedViolation.java
src/main/java/sorald/event/models/WarningLocation.java
src/main/java/sorald/sonar/GreedyBestFitScanner.java
src/main/java/sorald/sonar/RuleViolation.java
src/main/java/sorald/sonar/ScannedViolation.java

#166 
Replaces `RuleViolation.getFileName` (which returns `String`) with `RuleViolation.getAbsolutePath` (which returns an absolute and normalized `Path`)

refactor: Replace RuleViolation.getFileName() with RuleViolation.getAbsolutePath()

---

src/main/java/sorald/processor/DeadStoreProcessor.java
src/main/java/sorald/processor/SoraldAbstractProcessor.java
src/test/resources/processor_test_files/1854_DeadStore/DeadVariableWithMultipleDeadStores.java
src/test/resources/processor_test_files/1854_DeadStore/DeadVariableWithMultipleDeadStores.java.expected
src/test/resources/processor_test_files/1854_DeadStore/MultipleDeadStoresInARow.java
src/test/resources/processor_test_files/1854_DeadStore/MultipleDeadStoresInARow.java.expected

Fix #418 
This PR fixes a problem where the `DeadStoreProcessor` would merge a declaration with a dead initializer, with _another_ dead store (/facepalm). The fix is pretty simple: don't do that.
Here's an example of how moving the declaration without considering dead stores can go wrong:
```diff
public class MultipleDeadStoresInARow {
public static void main(String[] args){
-       int a = 2; // Noncompliant
-       a = 3; // Noncompliant
+       int a = 3;
a = 4;
System.out.println(a);
}
} 
```
Note that the initializer for `a` is still a dead store. The problem is that the dead store that's mapped to `a = 3` will simply disappear, as that element is replaced with the declaration.
Here's the same fix after the patch in this PR:
```diff
public class MultipleDeadStoresInARow {
public …
```

fix(1854): Avoid merging declaration with another dead store

---

.github/workflows/tests.yml

Fix #423 
This cleans up the CI output by separating building the project and running tests into separate steps. Thus, the "Run tests" step is not polluted by thousands of lines of "Downloading some dependency".
Previously, the "Build project" step both fetched dependencies and ran tests. Now, the new "Run tests" step only runs tests, which makes it easier to find the test output. Arguably, we should also turn off the logger or set it to warnings only, but that's for another PR.
* [See this build for a "before"](https://github.com/SpoonLabs/sorald/actions/runs/659434600)
* [See this build for an "after"](https://github.com/SpoonLabs/sorald/runs/2128668398)

chore: Separate building and testing into different steps

---

pom.xml

This PR just updates Spoon to the latest beta. Notably, this includes my patch for parenthesis minimization in arithmetic expressions. As an example, here's what a `CastArithmeticOperand` repair in Verificatum looked like before the patch:
```diff
-                ((double) (widthExp + (2 - 1 / widthExp) * bitLength)) / width;
+                ( (double) (widthExp + ((2 - (1D / widthExp)) * bitLength))) / width;
```
And here's what it now looks like:
```diff
-                ((double) (widthExp + (2 - 1 / widthExp) * bitLength)) / width;
+                ( (double) (widthExp + (2 - 1D / widthExp) * bitLength)) / width;
```
Not that the redundant parentheses around `1D / widthExp` are now gone.
There's still a rogue space at the start, but that's just the sniper printer mismatching one of …

chore: Use Spoon 8.4.0-beta-18

---

.github/workflows/tests.yml

Fix #424 
This PR adds caching of Maven dependencies to the GitHub Actions workflows. The cache is used for at most 24 hours as the cache key is tied to the date. Unfortunately, the caching steps must be duplicated across jobs, as there is no way to reuse steps in Actions at the moment.
I recently introduced this in Spoon as well: inria/spoon#3842
Before and after times should speak for themselves:
* [Before](https://github.com/SpoonLabs/sorald/actions/runs/660335885): total = 4m57s
* [After](https://github.com/SpoonLabs/sorald/actions/runs/660347955): total = 2m48s

chore: Add daily Maven dependency cache to all jobs

---

pom.xml
src/test/resources/logback.xml

Fix #427 
It's super hard to read test failures because of the massive amounts of INFO log output from SonarJava. This PR sets the log output to WARNING for tests, such that all of that redundant output is hidden.

chore: Set log level to WARNING in tests

---

src/main/java/sorald/Constants.java
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/FileUtilsTest.java
src/test/java/sorald/MavenHelper.java
src/test/java/sorald/MavenLauncherTest.java
src/test/java/sorald/RepairTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/TargetedRepairTest.java
src/test/java/sorald/TestHelper.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/java/sorald/processor/BestFitScannerTest.java
src/test/java/sorald/processor/MaxFixesPerRuleTest.java
src/test/java/sorald/processor/NoSonarTest.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java
src/test/java/sorald/segment/FirstFitSegmentationAlgorithmTest.java
src/test/java/sorald/segment/SoraldTreeBuilderAlgorithmTest.java
src/test/java/sorald/sonar/RuleVerifierTest.java
src/test/java/sorald/sonar/RuleViolationTest.java

The PATH_TO_RESOURCES_FOLDER constant should not be available in production, as it's only used for tests. This PR moves it into an appropriate position.

refactor: Move PATH_TO_RESOURCES_FOLDER to TestHelper

---

README.md
src/main/java/sorald/Constants.java
src/main/java/sorald/Repair.java
src/main/java/sorald/SoraldConfig.java
src/main/java/sorald/cli/RepairCommand.java
src/test/java/sorald/FileOutputStrategyTest.java
src/test/java/sorald/RepairTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/processor/MaxFixesPerRuleTest.java
src/test/java/sorald/processor/NoSonarTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

#409 
This is in preparation of removing out-of-place repair. With that gone, there is no need for a separate workspace directory, and consequently there is no need for a CLI argument to specify it.
Note that this PR only removes the workspace argument, the workspace is still used for out-of-place repair but is hard-coded to `sorald-workspace`. I will follow up on this PR with a couple more such that, in the end, out-of-place repair is gone. See #432 for the complete (but pretty messy) vision.

break: Remove --workspace argument

---

src/main/java/sorald/cli/RepairCommand.java
src/test/java/sorald/TargetedRepairTest.java

Fix #395 
Adds validation to user-specified rule violations by checking that the precise violations specified actually exist. To be clear, it validates that violations specified like so exist:
```
$ sorald repair --violation-specs 2111:2111_BigDecimalDoubleConstructor/BigDecimalDoubleConstructor.java:21:25:21:45 [...]
```
Previously, this was limited to the specified file existing. This new behavior is made possible by _always_ mining violations, which is something we'll need to do to implement #358 as well.
A downside is that this adds a performance overhead to specifying rule violations, as it requires a scan with Sonar that would otherwise not be necessary as we'd just assume that they are real. But, I think I'm pretty much the only one who currently uses targeted repair (I use it when …

feat: Validate violation specs

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/main/java/sorald/sonar/RuleViolation.java
src/main/java/sorald/sonar/ScannedViolation.java

Fix #358 
This adds a method `RuleViolation.getMessage()` that can be used to fetch the message emitted by Sonar. The reason we want this message is that it sometimes contains useful information. As a driver for the implementation and to illustrate that it's useful, I've refactored `CastArithmeticOperandProcessor` to use the message to parse the expected type.
See #375 for why it's proven inconvenient to try to get the type ourselves. Unfortunately, the test case provided there no longer causes a failure, as SonarJava does not flag a violation of rule 2184 inside method calls, it's only for assignments. The new, better position matching thus makes it impossible to trigger the bug, but it's still guaranteed to be gone as the method in which it was triggered `getExpectedtype()` has been …

feat: Add message to rule violation

---

.github/workflows/tests.yml
README.md
experimentation/tools/README.md
experimentation/tools/sorald/benchmark.py
experimentation/tools/sorald/warnings_extractor.py
experimentation/tools/tests/resources/prs_final.json
experimentation/tools/tests/resources/prs_initial.json
experimentation/tools/tests/resources/stats.json
src/main/java/sorald/Constants.java
src/main/java/sorald/Repair.java
src/main/java/sorald/SoraldConfig.java
src/main/java/sorald/cli/MineCommand.java
src/main/java/sorald/cli/RepairCommand.java
src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/MavenLauncherTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/TargetedRepairTest.java
src/test/java/sorald/event/collectors/CompilationUnitCollectorTest.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/java/sorald/processor/MaxFixesPerRuleTest.java
src/test/java/sorald/processor/NoSonarTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

Fix #429 
This PR renames the argument, and also updates all corresponding variable names in the source code, as well as updating docs and scripts.
I swear that I did not mistype the argument in `Rename --origina-files-path arg to --source` on purpose; it's just really error prone! :)

break: Rename --original-files-path arg to --source

---

pom.xml

We shouldn't declare the snapshot repository willy-nilly in the pom-file, see discussion over at inria/spoon#3216. This PR puts the snapshot repo in a profile, such that we can still easily access it when we want like so:
```
$ mvn -P spoonSnapshot ...
```

chore: Move Spoon snapshot repo into a profile

---

pom.xml

Fix #445 
Updates to Spoon 9.1.0-beta-2.
This version includes a bugfix for the sniper printer, where it failed to print a newline when adding elements to the beginning of a statement list/method list. Where previously some of our patches that add to the beginning of a class body or statement list would look like this:
```diff
-public class CtLineElementComparator implements Comparator<CtElement>, Serializable {
+public class CtLineElementComparator implements Comparator<CtElement>, Serializable {static final long serialVersionUID = 1L;
```
They now look like this:
```diff
public class CtLineElementComparator implements Comparator<CtElement>, Serializable {
+       static final long serialVersionUID = 1L;
```

chore: Use Spoon 9.1.0-beta-2

---

docs/HANDLED_RULES.md
src/main/java/sorald/processor/SerialVersionUidProcessor.java
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/NestedInAbstract.java.expected
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/NestedInNestedGuiClass.java.expected
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/NestedInThrowable.expected
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/NonSerial.java.expected
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/SupertypeImplementsSerializable.java.expected
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/UpperClass.java.expected

Fix #457 
Adds the `private` visibility to a `serialVersionUID` field if the field is _created_ by the processor, rather than the processor modifying an existing field. It makes most sense to make new fields private, as they're guaranteed not to be accessed anywhere else in the project (as they didn't exist prior to the repair!).

feat(2057): Make newly added serialVersionUID field private

---

.github/workflows/tests.yml
src/main/java/sorald/FileUtils.java
src/main/java/sorald/cli/RealFileConverter.java
src/main/java/sorald/cli/RepairCommand.java
src/main/java/sorald/sonar/BestFitScanner.java
src/test/java/sorald/FileUtilsTest.java
src/test/java/sorald/TestHelper.java

Fix #416
Fix #428
This PR adds a macOS build and fixes all test errors on macOS. They're all related to symbolic links. When creating a temporary directory on macOS (which we do e.g. in `TestHelper.createTemporaryTestResourceWorkspace()`), it's created in the `/var` directory. However, that's actually a symlink to `/private/var`, but the path you get back starts with `/var`. This causes problems, as Spoon always fully resolves symlinks while Sorald otherwise does not.
In order to debug and test this on a non-macOS system, I also added a hidden part to the test suite: if you set the environment variable `SORALD_TEST_SYMLINK_WORKSPACE=true`, then `TestHelper` returns a symlink to the temporary workspaces it creates, rather than a real path to the workspace. This does not however need to be …

fix: Handle symlinks in input (add macOS support)

---

src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/test/resources/processor_test_files/2142_InterruptedException/CatchMultipleTypes.java
src/test/resources/processor_test_files/2142_InterruptedException/CatchMultipleTypes.java.expected
src/test/resources/processor_test_files/2142_InterruptedException/InterruptedExceptionForTesting.java.expected

Fix #459 
This PR makes the `InterruptedExceptionProcessor` insert a type check when a catch clause catches more than just an `InterruptedException`. This is to avoid setting the interrupt flag when something other that `InterruptedException` was actually caught. Here's an example transformation:
```diff
public class CatchMultipleTypes {
public static void method() {
try {
if (1 < 2) {
throw new ExecutionException(new RuntimeException());
} else {
throw new InterruptedException();
}
} catch (InterruptedException | ExecutionException e) { // Noncompliant
+            if (e instanceof InterruptedException) {
+                Thread.currentThread().interrupt();
+            }
throw new RuntimeException(e);
}
}
}
```
I need this to fix a [violation in …

feat(2142): Add type check when catch clause contains multiple types

---

docs/CONTRIBUTING.md
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java
src/test/resources/processor_test_files/1854_DeadStore/DeadVariableWithMultipleDeadStores.java.exact
src/test/resources/processor_test_files/2057_SerialVersionUidCheck/UpperClass.java.exact

Fix #393 
This PR adds the long-awaited functionality to test exact, literal output from Sorald. See the updated `CONTRIBUTING.md` file (cc4ccd4) for how to use it.

test: Extend test suite to be able to test exact literal matches

---

src/main/java/sorald/Constants.java
src/main/java/sorald/FileUtils.java
src/main/java/sorald/Processors.java
src/main/java/sorald/cli/Cli.java
src/main/java/sorald/event/EventHelper.java
src/main/java/sorald/event/StatsMetadataKeys.java
src/main/java/sorald/segment/FirstFitSegmentationAlgorithm.java
src/main/java/sorald/segment/SoraldTreeBuilderAlgorithm.java
src/main/java/sorald/sonar/ProjectScanner.java
src/main/java/sorald/sonar/RuleVerifier.java
src/main/java/sorald/support/IdentityHashSet.java

Hi,
This PR fixes 11 violations of [Sonar Rule 1118: 'Utility classes should not have public constructors'](https://rules.sonarsource.com/java/RSPEC-1118).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 1118](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#utility-classes-should-not-have-public-constructors-sonar-rule-1118).

fix: Fix violations of Sonar rule 1118

---

pom.xml

Sonatype requires that the pom file contains [developer information](https://central.sonatype.org/pages/requirements.html#developer-information). Here's for example the corresponding entry in Depclean: https://github.com/castor-software/depclean/blob/add262810f6d1b93b44d31431d69c7d14cad1cd6/pom.xml#L62-L70
I figured we'll just put the currently active developers, which would be at least myself, and then possibly @fermadeiral and @khaes-kth. @fermadeiral @khaes-kth would you like to be added, and if so, with what details (email, organization etc)?
What should we put as organization? Since we're publishing under Castor's group id, I suppose we put Castor there? Perhaps it doesn't really matter, we could just put "KTH" for everyone.

chore: Add developer information to pom.xml

---

src/main/java/sorald/processor/CastArithmeticOperandProcessor.java
src/test/resources/processor_test_files/2184_CastArithmeticOperand/LiteralIntOperand.java.exact

fix(2184): Make CastArithmeticOperand use uppercase literal suffix

---

.github/workflows/tests.yml
experimentation/tools/sorald/_helpers/soraldwrapper.py
experimentation/tools/sorald/warnings_extractor.py
pom.xml

#150 
This PR sets the version number to 0.1.0-SNAPSHOT and updates support scripts that had the old version number hard coded.

chore: Set version to 0.1.0-SNAPSHOT

---

pom.xml

#150 
See https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#extra-setup-for-pomxml

chore: Prevent gpg-maven-plugin from using pinentry programs

---

src/main/java/sorald/cli/SoraldVersionProvider.java

This avoids a false positive for rule 3032 discussed in #470.

refactor: Avoid explicitly accessing getClassLoader()

---

.github/workflows/deploy.yml

Fix #477 
This PR edits the deploy job to only run if the repository is called `SpoonLabs/sorald` (i.e. does not run on forks, where it will always fail!)

chore: Only run deploy job in SpoonLabs/sorald

---

.github/workflows/tests.yml
experimentation/tools/sorald/_helpers/soraldwrapper.py

Fix #483 
This PR simply removes the expectation that the compiled JAR file is a SNAPSHOT version, which is important for release commits.

fix: Make support scripts/CI workflows find any version of the Sorald JAR

---

.github/mem-constrained-exec.sh
.github/workflows/tests.yml
src/main/java/sorald/Repair.java
src/main/java/sorald/event/collectors/CompilationUnitCollector.java

Fix #437 
This fixes a memory leak in segment mode caused by the CompilationUnitCollector retaining references to already printed compilation units. Also replaces the JAR sanity check test with a highly memory-constrained test, using the packaged JAR in segment mode. [Here's an example of where it reproduces the memory leak](https://github.com/SpoonLabs/sorald/pull/498/checks?check_run_id=2410450540#step:11:30).
The memory constrained test takes as long to run as all of the unit tests combined, but I think that's fine considering that it adds a real-world test to the test suite. Note that it also asserts the amount of repairs (170) for the given rule, so it's the largest-scale test we have right now.

fix: Fix memory leak from accumulating compilation units across writes

---

.github/mem-constrained-exec.sh

Another one of those hard-coded SNAPSHOT paths had snuck its way into the CI. It works fine as long as the current version in the repository is a SNAPSHOT version, but blows up on releases.
This PR simply removes `SNAPSHOT-` from the file path.

chore: Remove SNAPSHOT from path in memory-constrained test script

---

.github/workflows/deploy.yml

Related to #482 
This adjusts the deploy workflow such that it only deploys non-snapshot versions once a GitHub release is published. This makes the release process a bit more predictable than when deploying from master, as GitHub Actions typically only builds the very latest commit, which when pushing a release is in fact the "next iteration" commit, and not the release commit.
I had an awkward workaround for this (push the release commit, then wait until the action starts, then push the next iteration commit). By deploying only on a published release, that workaround is no longer necessary, and it also allows us to release _before_ merging into master. That's good if there's trouble in the publish step.

chore: Only run non-SNAPSHOT publish step on publish of release

---

codecov.yml

Fix #497 
The Codecov PR comment is large and in the way, let's get rid of it. We're really only interested in the check, if we want the report we can go to codecov.io.
I think that the change only takes effect once merged into master.

chore: Disable PR comment

---

src/test/java/sorald/TargetedRepairTest.java

Fix #480 
The problem described in #480 turned out to not be reproducible. Perhaps I was using an old version, or there were some very specific circumstances I failed to record.
Anyway, I'll just add a single test case that performs the task I had trouble with (doing targeted repair when `--source` points to a file) to see that we don't get any regressions.

test: Add test case for doing targeted repair of specific file

---

.github/workflows/tests.yml

Fix #506 
This prevents failing the workflow when a PR comes in from a fork.

chore: Only run Sonar step on the main repository

---

.github/workflows/sorald_buildbreaker.yml

The old version is not working anymore. I'll merge this myself as it's a trivial change and I need it right away.

chore: Use latest version of sorald-buildbreaker

---

.github/workflows/tests.yml

Fix #512 
There was a bit of a bug in skipping Sonar on PRs from fork (read: it didn't skip Sonar on PRs from forks). With this PR, that's fixed.
* You can see here that with this PR running from a fork, [the Sonar step doesn't run](https://github.com/SpoonLabs/sorald/pull/520/checks?check_run_id=2508555655)
* And in this PR (which originates from within this repo), [the Sonar step does run](https://github.com/SpoonLabs/sorald/pull/519/checks?check_run_id=2508557275#step:12:1)

chore: Disable Sonar on PRs from forks

---

src/main/java/sorald/sonar/BestFitScanner.java
src/test/resources/processor_test_files/1854_DeadStore/JointLocalVarDeclaration.java
src/test/resources/processor_test_files/1854_DeadStore/JointLocalVarDeclaration.java.expected
src/test/resources/processor_test_files/1854_DeadStore/MultiLineJointLocalVariableDeclarations.java
src/test/resources/processor_test_files/1854_DeadStore/MultiLineJointLocalVariableDeclarations.java.expected

Fix #522 
This PR extends the best fits scanner with a post filter that runs on all position-matched candidates. Currently, this post filter is only used to improve matching between rule violations and jointly declared variables.
@lyxell I know we discussed hamming distance, but I figured an exact match should be equally viable here. It may be that we find corner cases where the entire identifier can't be extracted, but I couldn't come up with one. Feel free to suggest more test cases and comment on the implementation!

fix: Add exact-match search on variable name in joint declarations

---

.github/workflows/tests.yml

This PR bumps codecov-action to v1.5.0. The big difference is that the bash uploader (which was the cause of the security breach mentioned in #485) is integrated into the action rather than being fetched from a remote source, making it much more secure.

chore: Use codecov-action v1.5.0

---

src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/test/resources/processor_test_files/2142_InterruptedException/CatchMultipleTypes.java.exact

Fix #526 
This PR amends the `InterruptedExceptionProcessor` to put curly brackets around inserted if-statements. Previously, it would look like so:
```diff
try {
job.get();
} catch (InterruptedException | ExecutionException e) {
+                               if (e instanceof InterruptedException)
+                                       Thread.currentThread().interrupt();
+
throw new SpoonException("failed to wait for parallel processor to finish", e);
}
}
```
but with this patch it looks like so:
```diff
try {
job.get();
} catch (InterruptedException | ExecutionException e) {
+                               if (e instanceof InterruptedException) {
+                                       Thread.currentThread().interrupt();
+                               }
+
throw new …
```

feat(2142): Put curly brackets around inserted if-statement

---

pom.xml

Bumps the version of Spoon to 9.1.0-beta-9. This includes a fix for a bug that caused simply qualified names in catchers with union types to become fully qualified (see inria/spoon#3918).
Here's an example of the bug in action in repairing a violation of rule 2142:
```diff
try {
job.get();
-                       } catch (InterruptedException | ExecutionException e) {
+                       } catch (java.lang.InterruptedException | java.util.concurrent.ExecutionException e) {
+                               if (e instanceof InterruptedException) {
+                                       Thread.currentThread().interrupt();
+                               }
throw new SpoonException("failed to wait for parallel processor to finish", e);
}
}
```
And here's the same repair where the bug is …

chore: Use Spoon version 9.1.0-beta-9

---

README.md
src/main/java/sorald/Constants.java
src/main/java/sorald/cli/MineCommand.java
src/main/java/sorald/miner/MineSonarWarnings.java
src/main/java/sorald/util/MavenUtils.java
src/test/java/sorald/miner/WarningMinerTest.java

Fix #523, related to #533 
This PR implements classpath resolution for Maven projects for the miner. I decided to go with adding a flag `--resolve-classpath-from <path-to-project-root>`, that currently only works for Maven projects (there must be a file `<path-to-project-route>/pom.xml`).
I chose to go this route instead of adding e.g. `--maven` or `--miner-mode MAVEN`, as we can quite easily add support for other build systems and just infer them by looking for build files. For example, to add support for Gradle, and then probably use the `gradle dependencies` command in some way. In other words, we can add support for more build systems without changing the CLI.
Initially I opted for just a `--resolve-classpath` argument that uses the `--source` path as the project route, but as I ran …

feat: Add classpath resolution for Maven projects to miner

---

README.md

The link in the README that points to the release is hard-coded to 0.1.0. This PR points it to the `latest` endpoint instead, which updates automatically with each new release.

doc: Fix outdated release link

---

src/main/java/sorald/Repair.java
src/main/java/sorald/cli/BaseCommand.java
src/main/java/sorald/cli/MineCommand.java
src/main/java/sorald/cli/RepairCommand.java
src/test/java/sorald/ClasspathModeTest.java
src/test/java/sorald/RepairTest.java
src/test/java/sorald/SegmentStrategyTest.java

Fix #533 
This PR adds the `--resolve-classpath-from <path-to-project-root>` option to the repair command. It works precisely the same way as for the mine command, and resolves the classpath from the provided directory path. Currently only works for Maven projects.
While this allows us to run Spoon in noclasspath mode in most cases, I chose to disable it for now. The reason is that segment mode won't work in noclasspath mode even with the classpath provided, as this classpath only includes dependencies, and then parts of the project itself would be missing in each segment. A solution would be to require the project to be compiled before-hand, and include the project's own bytecode on the classpath as well, but I feel that's too much to squeeze into this single PR.

feat: Add `--resolve-classpath-from` to repair command

---

src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/test/resources/processor_test_files/2095_UnclosedResources/MultipleCloseablesInSingleTry.java
src/test/resources/processor_test_files/2095_UnclosedResources/MultipleCloseablesInSingleTry.java.expected
src/test/resources/processor_test_files/2095_UnclosedResources/UnclosedResourceWithinTryWithResources.java
src/test/resources/processor_test_files/2095_UnclosedResources/UnclosedResourceWithinTryWithResources.java.expected

Fix #386 
This PR is a minor extension to the `UnclosedResourcesProcessor` that simply makes it respect an existing try-with-resources, and add resources to it rather than delete it and create a new one (which would cause resources to be lost; only the very last resource processed would ever appear in the resource block of the try). By extension, this allows the processor to deal with multiple unclosed resources in the same try-block. Here's how that works:
1. There's one violation for each unclosed resource
2. The first violation is fixed first (due to iteration order of the AST), and creates a try-with-resources block, with any remaining violating elements being placed within it
3. Any further violations are fixed simply by deleting the violating element and adding it the the (now …

feat(2095): Handle multiple unclosed closeables in same try

---

src/main/java/sorald/processor/UnusedThrowableProcessor.java
src/test/resources/processor_test_files/3984_UnusedThrowable/SingleUnusedThrowable.java
src/test/resources/processor_test_files/3984_UnusedThrowable/SingleUnusedThrowable.java.exact
src/test/resources/processor_test_files/3984_UnusedThrowable/SingleUnusedThrowable.java.expected

Fix #554 
This PR fixes a problem where the `UnusedThrowableProcessor` always creates a fully qualified name for the throwable, even when a simply qualified name is used initially. I.e. the repair looks like so:
```java
-new IllegalArgumentException();
+throw new java.lang.IllegalArgumentException();
```
With this fix, the repair looks as intended:
```java
-new IllegalArgumentException();
+throw new IllegalArgumentException();
```
In doing the exact match test to check that the printed reference is indeed simply qualified, I also discovered that comments on the thrown expression must be moved to the `CtThrow`, otherwise they are printed like this before the semicolon:
```java
throw new IllegalArgumentException()// here's a comment
;
```
And that just looks very strange.

fix(3984): Retain simply qualified name of throwable type

---

src/main/java/sorald/processor/DeadStoreProcessor.java
src/test/resources/processor_test_files/1854_DeadStore/UnaryOpsInStatementPosition.java
src/test/resources/processor_test_files/1854_DeadStore/UnaryOpsInStatementPosition.java.expected

Fix #546 
This PR is a very minor extension to the `DeadStoreProcessor` that makes it just delete unary operators in statement position, as their return values can't possibly be read (because they're in statement position!).
When I opened #546 such unary operators were just ignored, but now the actually cause a crash. So this PR is doubly needed!

fix(1854): Fix handling of unary operators in statement position

---

.github/workflows/tests.yml
codecov.yml

Codecov fails sporadically, so we don't want to fail the build if it fails to upload.
Perhaps it's time to switch to Coveralls.

chore: Do not fail build if Codecov fails

---

src/main/java/sorald/processor/UnclosedResourcesProcessor.java

I got stuck trying to fix #540 because this processor is a bit complex. This PR completely refactors the `UnclosedResourcesProcessor` to make it easier to reason about.

refactor(2095): Refactor UnclosedResourcesProcessor

---

src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/test/resources/processor_test_files/2095_UnclosedResources/OneClosedOneUnclosed.java
src/test/resources/processor_test_files/2095_UnclosedResources/OneClosedOneUnclosed.java.expected

Fix #540 (this is actually supposed to fix #540, not a mistake this time!)
This PR changes the `UnclosedResourcesProcessor` to retain the finally block when converting a try to a try-with-resources. Previously, it would just drop the finally block.

fix(2095): Retain finally-block from try when converting to try-with-resources

---

src/main/java/sorald/processor/UnclosedResourcesProcessor.java
src/test/resources/processor_test_files/2095_UnclosedResources/BadCloseInFinally.java
src/test/resources/processor_test_files/2095_UnclosedResources/BadCloseInFinally.java.expected
src/test/resources/processor_test_files/2095_UnclosedResources/ReferenceInCatcher.java
src/test/resources/processor_test_files/2095_UnclosedResources/ReferenceInCatcher.java.expected
src/test/resources/processor_test_files/2095_UnclosedResources/ReferenceInCatcherAndFinalizerToFieldWithSameNameAsResource.java
src/test/resources/processor_test_files/2095_UnclosedResources/ReferenceInCatcherAndFinalizerToFieldWithSameNameAsResource.java.expected
src/test/resources/processor_test_files/2095_UnclosedResources/UnclosedResourceWithinTryWithResources.java.expected

Fix #561 
This PR makes the UnclosedResourcesProcessor clean up references to the variable that was inlined into the resource block. Previously, such left-over references were not cleaned up, causing compile errors.
Here's an example of the new-and-improved repair, note how it removes the `if` in the catcher:
```diff
public class ReferenceInCatcherAndFinalizerToFieldWithSameNameAsResource {
private int bw = 2;
public void saveTo(File file) throws IOException {
-        BufferedWriter bw = null;
-        try {
-            bw = new BufferedWriter(new FileWriter(file)); // Noncompliant
+        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
bw.write("Write some stuff to file");
} catch (IOException e) {
e.printStackTrace();
System.out.println(this.bw); // reference to …
```

fix: Clean up out-of-scope references to auto-managed resource

---

src/test/java/sorald/processor/ProcessorTestFilesCompileTest.java
src/test/resources/processor_test_files/2755_XxeProcessing/InsecureTransformerFactoryUsage.java.expected

Fix #565 
This PR adds a test that runs through all Java input files and `.expected` Java files in `src/test/resources/processor_test_files` that are not prefixed and with `NOCOMPILE` and tries to compile them. If compilation fails, the test reports output like so:
```java
org.opentest4j.AssertionFailedError: /tmp/junit5557181061285140448/InsecureTransformerFactoryUsage.java:11: error: cannot find symbol
TransformerFactory transformerFactory = createTrnsformerFactory();
^
symbol:   method createTrnsformerFactory()
location: class InsecureTransformerFactoryUsage ==> 
Expected :true
Actual   :false
```
Previously, the only verification we had that test resources compiled like they should was one of the Maven mode tests, and that would fail with a pretty non-obvious error message. It also …

test: Verify that processor test resources compile

---

src/test/java/sorald/Assertions.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestFilesCompileTest.java

Fix #563 
This PR adds a test case that checks that files that are compilable before repair, are also compilable after. There are two test cases that fail, `CastArithmeticOperand.java` and `MathOnFloat.java`. Both fail due to "potentially lossy conversion from double to float".
[Link to failures](https://github.com/SpoonLabs/sorald/runs/2818084309?check_suite_focus=true#step:10:905).

test: Verify that compilable Java files still compile after repair

---

src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/processor/ProcessorTest.java
src/test/java/sorald/processor/ProcessorTestFilesCompileTest.java
src/test/java/sorald/processor/ProcessorTestHelper.java

Fix #573 
The cause of #573 was that the compile test introduced in #566 produced .class files in the test resources directory. These class files would then cause the surefire plugin to crash for some reason. I don't know why it crashes because of that, but the class files shouldn't be there either way.
This also explains why only the deploy job failed: it runs the tests twice, once when running `package` and once when running `deploy` (we should probably remove the `package` target). All of the other jobs run the tests only once, and thus don't encounter the problem.
The reason this happened was that there are two overloads of the `ProcessorTestHelper.getTestCaseStream()` method. One of them returns the test cases for the resources in a directory (this was the one that was used), and the …

fix: Fix test errors caused by compile output in test resources

---

src/main/java/sorald/event/collectors/MinerStatisticsCollector.java
src/main/java/sorald/event/models/miner/MinedRule.java

#331 
The package containing `ImmutableList` is a transitive dependency of Sorald through SonarJava. It's not there anymore in SonarJava 7+, and so this PR removes the two uses of it. The same functionality is available as unmodifiable lists in the standard library, so I don't think it's a good idea to pull in a dependency just for this.

refactor: Replace use of ImmutableList with List.copyOf

---

docs/CONTRIBUTING.md
src/main/java/sorald/processor/CollectionIsEmptyProcessor.java
src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java
src/main/java/sorald/util/Transformations.java

Fix #572 
This PR adds a new `Transformations` utility class, which is meant to house reusable high-level transformation methods for use across the entire project. If we look through the project, I think we'll find many more recurring transformations that can be extracted into this class.
Note that this class is specifically for transformations. I think that if we want reusable Spoon-"something else", we should create another class with an appropriate name for that.

refactor: Extract not method into Transformations utility class

---

README.md

As noted in #273, we currently don't support Windows, but there's really no mention of that anywhere other than the issue tracker. In the past year, two Windows users have reported problems, see #335 and #589.
This PR adds a badge at the top of the README with the supported platforms, as well as some text in the `Prerequisites` section.

doc: Add badge and text on platform support

---

.github/workflows/tests.yml
README.md
src/main/java/sorald/sonar/ScannedViolation.java
src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/TargetedRepairTest.java

fix #589, fix #335
Partially addresses #273 
This PR adds _core_ support for Windows, along with a Windows build in the CI. Note that statistics gathering, targeted repair and segment mode tests are not passing: they are currently disabled on Windows.

feat: Add Windows support

---

docs/HANDLED_RULES.md
experimentation/tools/sorald/handled_rules.py

A small typographical error in the link to `handled_rules.py` has been fixed in this PR. Unrelated to this change, many whitespaces have also been removed even though I didn't edit that particular part of the template.

fix: Fix linking of `handled_rules.py`

---

src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/test/resources/processor_test_files/S2142_InterruptedException/CatchBlockWithBreak.expected
src/test/resources/processor_test_files/S2142_InterruptedException/CatchBlockWithBreak.java
src/test/resources/processor_test_files/S2142_InterruptedException/CatchBlockWithContinue.expected
src/test/resources/processor_test_files/S2142_InterruptedException/CatchBlockWithContinue.java

fix: Check for flow breaks before patching with the repair for S2142

---

src/test/java/sorald/ClasspathModeTest.java
src/test/java/sorald/MavenLauncherTest.java
src/test/java/sorald/miner/WarningMinerTest.java

Fixes #612 
After a [long debugging session](https://github.com/INRIA/spoon/pull/4272) with @slarse , we finally decided to disable our custom security manager (`SystemExitHandler`) as that was causing problems. See [this comment](https://github.com/actions/virtual-environments/issues/4485#issuecomment-968115508) for explanation.

fix: disable custom security manager for tests which indirectly look up the path of `mvn` executable

---

src/main/java/sorald/SelectiveForceImport.java

Reference #602 
I thought I would refactor the code first as suggested by @slarse. 
> Just glancing at that code I would begin with wrapping that map in a set (with Collections.newSetFromMap), because the values aren't used :)

refactor: store excluded references in a set which wraps `IdentityHashMap`

---

pom.xml

```
-------------------------------------------------------
D E P C L E A N   A N A L Y S I S   R E S U L T S
-------------------------------------------------------
USED DIRECT DEPENDENCIES [7]: 
org.eclipse.jgit:org.eclipse.jgit:5.7.0.202003110725-r:compile (2 MB)
org.sonarsource.java:java-checks:6.9.0.23563:compile (2 MB)
fr.inria.gforge.spoon:spoon-core:10.0.1-SNAPSHOT:compile (1 MB)
org.sonarsource.java:java-frontend:6.9.0.23563:compile (909 KB)
info.picocli:picocli:4.5.2:compile (381 KB)
commons-io:commons-io:2.7:compile (269 KB)
org.json:json:20190722:compile (63 KB)
USED INHERITED DEPENDENCIES [0]: 
USED TRANSITIVE DEPENDENCIES [31]: 
org.bouncycastle:bcprov-jdk15on:1.64:compile (4 MB)
org.sonarsource.sonarqube:sonar-plugin-api:7.9:compile (3 MB) …
```

chore: remove org.reflections:reflections

---

README.md

The changes update the badge because Travis was removed long ago. See https://github.com/SpoonLabs/sorald/pull/261.

docs: update tests' status badge

---

src/main/java/sorald/processor/BigDecimalDoubleConstructorProcessor.md
src/test/resources/processor_test_files/S2111_BigDecimalDoubleConstructor/BigDecimalDoubleConstructor.java

The processor for `S2111` already handled the case when `new BigDecimal` has more than two arguments, but it was not documented in the processor test file. The description of S2111 was also slightly misleading. Starting the description with "Any constructor ..." and then talking about a case where it has more than one argument defeats the purpose of generalising in the first statement.
P.S. This is the second time we will test the script `handled_rules.py`. I am really looking forward to it :)

docs: update tests files and description for S2111

---

src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java
src/test/resources/processor_test_files/S1860_SynchronizationOnStringOrBoxed/SynchronizationOnSimilarVariables.java
src/test/resources/processor_test_files/S1860_SynchronizationOnStringOrBoxed/SynchronizationOnSimilarVariables.java.expected

Sorald does not generate multiple variables with the same hashcode in different classes, as it considers the hashcode to be the unique ID that represents a variable. As an example, see [this](https://github.com/khaes-kth/sorald/blob/fix/SyncronizationOnSimilarVariables/src/test/resources/processor_test_files/S1860_SynchronizationOnStringOrBoxed/SynchronizationOnSimilarVariables.java#L14).
This PR fixes this by adding the variable's qualified name to its unique ID.

fix(SynchronizationOnStringOrBoxedProcessor): enables Sorald to generate multiple similar fields in separate classes for synchronization

---

pom.xml

Reference: https://github.com/SpoonLabs/sorald/pull/676#discussion_r766944428
The changes add a profile for downloading Spoon's SNAPSHOT when we want to try out new features in Spoon and cannot wait for its beta release.

chore: add profile for using spoon SNAPSHOT

---

.github/workflows/support.yml

I did not configure `JAVA_DISTRIBUTION` in `support.yml` and that's why the workflow failed.

chore: configure `env.JAVA_DISTRIBUTION` in support.yml

---

src/main/java/sorald/cli/RepairCommand.java

It is better to have the note under [this subsection](https://github.com/SpoonLabs/sorald#repairing-rule-violations-the-repair-command) next to all rule keys.

docs: explain incomplete rules after listing the rules

---

README.md

We don't need the long lists of usage in the README once #684 is merged.

docs: remove detailed description of subcommand from README

---

.gitignore

This was missing inside the `.gitignore`. The gitignore seems kinda small, have you thought about simply adding something like this https://www.toptal.com/developers/gitignore/api/java,visualstudiocode,eclipse,intellij,maven,gradle ?

chore: add factorypath to gitignore

---

src/main/java/sorald/processor/InterruptedExceptionProcessor.java
src/main/java/sorald/processor/InterruptedExceptionProcessor.md
src/test/resources/processor_test_files/S2142_InterruptedException/CatchMultipleTypes.java
src/test/resources/processor_test_files/S2142_InterruptedException/CatchMultipleTypes.java.exact
src/test/resources/processor_test_files/S2142_InterruptedException/CatchMultipleTypes.java.expected
src/test/resources/processor_test_files/S2142_InterruptedException/InterruptedExceptionForTesting.java.expected
src/test/resources/processor_test_files/S2142_InterruptedException/NOCOMPILE_RepairAndFieldTypePrint.java.exact

Fixes #697 
Before this gets merged, there is one thing we need to discuss. Consider the following case.
```java
catch (IOException | InterruptedException e) {
logger.error("Raising exception to connect runtime", e);
context.raiseError(e);
}
```
When we create another catch block for `InterruptedException`, should we or should we not copy the statements inside the original one? In this case, do we also need to copy `logger.error` and `context.raiseError` inside the new catch block we create? In my opinion, we should copy them as those statements, would be related to both the exception classes.
ToDo:

fix: repair of S2142 should not induce S1193 violation

---

experimentation/tools/tests/test_prmessage.py

We accidentally merged the jar of SonarJava plugin. It is not used in the code as-is and instead, we download it from maven so it does not need to be bundled with our package.

chore: Remove dependence of SonarJava jar plugin

---

experimentation/tools/sorald/handled_rules.py
experimentation/tools/tests/test_handled_rules.py

Fixes: #720 
We can now merge PRs without GHA submitting false-positive PRs - https://github.com/SpoonLabs/sorald/pull/721.
However, we should also open an issue for automatically updating the rule descriptions in the processors themselves.

chore: Parse rule title from processor to keep HANDLED_RULES.md in sync with processors

---

src/main/java/sorald/processor/SynchronizationOnStringOrBoxedProcessor.java

The smell was found by qodana and way too hard to automatic fix it. But the field was only queried but never updated. Queries against an empty hash map are hopefully not needed.

style: remove never updated field

---

src/test/java/sorald/GatherStatsTest.java
src/test/java/sorald/SegmentStrategyTest.java
src/test/java/sorald/TargetedRepairTest.java

Classical first PR trying to fix the CI on Windows.  The problems seems that the filename is simply the absolute path and not the relative path. How on earth this works on Unix is unknown to me. 
Fixes #273

review: fix CI on windows

---

README.md

I changed the supported platforms, the badge and one typo.

doc(readme): update supported platforms and fix typo

---

src/main/java/sorald/rule/StaticAnalyzer.java
src/main/java/sorald/sonar/ProjectScanner.java
src/main/java/sorald/sonar/SonarStaticAnalyzer.java

In #698 we had the discussion to add the `projectroot` as parameter for static analyzers because often they need it. This PR changes the interfaces and adds parameter to the interface. Furthermore, I would refactor the sonarlint-engine field to a local variable instead of a field, which is only used in a single method.

refactor: convert constructor args to method parameter and store `SonarLintEngine` as a local variable

---

pom.xml
src/main/java/sorald/sonar/ProjectScanner.java
src/main/java/sorald/sonar/SonarStaticAnalyzer.java

This PR loads all classes implementing `StaticAnalyzer` and invokes them. Fixes more or less the to-do inside the code. We could change `StaticAnalyzer` from interface to abstract class to enforce a non-arg constructor or hope the programmer writes his code correct. Only `StaticAnalyzer` with a non-arg constructor are usable for SPI.

feat: use SPI for analyzer loading

---

src/main/java/sorald/cli/MineCommand.java
src/main/java/sorald/rule/IRuleType.java
src/main/java/sorald/rule/Rule.java
src/main/java/sorald/rule/RuleType.java
src/main/java/sorald/rule/Rules.java
src/main/java/sorald/sonar/SonarRule.java
src/main/java/sorald/sonar/SonarRuleType.java
src/test/java/sorald/miner/WarningMinerTest.java
src/test/java/sorald/sonar/SonarRulesTest.java

Currently, the RuleType enum is used in alot of places. But there could exist more categories of bad smells than the 3 sonar ones. Using an interface in the code allows adding new categories easier, e.g., from other analyzers, without constantly changing the enum.

feat: abstract ruletype enum with IRuleType

---

sorald-parent/pom.xml

This PR creates a parent pom, containing all dependencies we need in all submodules. With this parent-pom we could choose to adopt a layout similar to spoon and move way less files.

refactor: create parent pom

---

pom.xml

An error exactly like https://stackoverflow.com/questions/56664609/maven-releaseprepare-with-noclassdeffounderror-while-using-git was thrown when I ran the edit script.

chore: fix release script

---

pom.xml

Used the `tools/sorald/release.py` to perform a release. I generated the changelog automatically using GitHub's option for now. It is not very easy to understand given that we are releasing after too long. We should probably perform releases more frequently and for that we need to document how frequently and upon what changes we release.
I went with a minor version upgrade because now we report all sonar violations instead of what was defined by `Checks`. There are many more feature introductions, of course.

chore: release sorald 0.4.0

---

README.md

`sorald` is now a sub-module of `sorald-parent` so the JAR is created there.

docs: update instructions for building JAR

---

sorald/src/main/java/sorald/rule/RuleProvider.java
sorald/src/test/java/sorald/sonar/SonarRulesTest.java

The APIs provided in `RuleProvider` were already implemented in `SonarRuleRepository` so I refactored the former class to use those implementations. This improves the code coverage and removed redundant code.
@MartinWitt could you please review it? I also had one question. `RuleProvider` is now a generic class - it can fetch rules for other static analyzers in future. Does this indicate that we put it inside `sorald-api`?

refactor: reuse APIs defined in RuleRepository in RuleProvider

---

sorald-api/src/main/java/sorald/cli/CLIConfigForStaticAnalyzer.java
sorald-api/src/main/java/sorald/rule/StaticAnalyzer.java
sorald/src/main/java/sorald/SoraldConfig.java
sorald/src/main/java/sorald/cli/MineCommand.java
sorald/src/main/java/sorald/cli/RepairCommand.java
sorald/src/main/java/sorald/miner/MineSonarWarnings.java
sorald/src/main/java/sorald/sonar/ProjectScanner.java
sorald/src/main/java/sorald/sonar/SonarStaticAnalyzer.java

These changes modify how options from CLI are passed through the program. As of now, each option, like `classpath`, was passed individually as an argument to the concerned methods. However, upon the addition of new options in the CLI, we would have to modify all those methods. This is not good coding practice. Thus, I refactored the methods to use a generic CLI option store to contain all the arguments passed to the program.

refactor: pass CLI context rather than individual parameter

---

.github/workflows/combine-prs.yml

Reference: https://github.com/SpoonLabs/sorald/issues/774
I created a [GitHub app](https://github.com/apps/combine-pr) to deal with the shortcomings listed in the above issue.

chore: create combined PR using GitHub app

---

sorald/src/main/java/sorald/event/collectors/RepairStatisticsCollector.java
sorald/src/test/java/sorald/GatherStatsTest.java

Fixes #863 
Phew ... this took a while to debug. Playing around in #864 made me realise that the repair time for some test was being reported incorrectly. As you can see [here](https://github.com/SpoonLabs/sorald/runs/7897645976?check_suite_focus=true#step:10:228), the `repairTimeMs` for one of the repairs is `0ms`, and in the tests we want it to be [greater than `0`](https://github.com/SpoonLabs/sorald/blob/master/sorald/src/test/java/sorald/GatherStatsTest.java#L81). I draw upon the following conclusion from my analysis - the repairs were performed in less than a millisecond so the difference was not captured by `repairEnd` and `repairStart` as they both were not precise enough.
I am using `System.nanoTime` for computing time in the changes because 1) it is more precise and 2) it seems …

chore: fix windows build failure

---

docs/CONTRIBUTING.md
sorald/src/test/java/sorald/Assertions.java
sorald/src/test/java/sorald/processor/ProcessorTest.java
sorald/src/test/java/sorald/processor/ProcessorTestHelper.java
sorald/src/test/resources/processor_test_files/S2164_MathOnFloat/INCOMPLETE_DoNotCastFloat.java

I felt the test was necessary so that we are sure that the violation is being detected, but we are intentionally not repairing it.

tests: add configuration to verify that MathOnFloatProcessor does skip repairs for Incomplete cases

---

pom.xml
sorald-api/pom.xml
sorald/pom.xml

I haven't been actively involved in this project for along time, so I think removing my name from the list(s) of developers. These are to my understanding for those actively maintaining the project and should not act as a historical account of contributors.

governance: Remove slarse as developer

---

pom.xml
sorald-api/pom.xml
sorald-api/src/main/java/sorald/annotations/IncompleteProcessor.java
sorald-api/src/main/java/sorald/event/SoraldEvent.java
sorald-api/src/main/java/sorald/processor/SoraldAbstractProcessor.java
sorald-api/src/main/java/sorald/rule/Rule.java
sorald-api/src/main/java/sorald/rule/RuleViolation.java
sorald/pom.xml
sorald/src/main/java/sorald/Processors.java
sorald/src/main/java/sorald/SelectiveForceImport.java
sorald/src/main/java/sorald/cli/Cli.java
sorald/src/main/java/sorald/event/collectors/CompilationUnitCollector.java
sorald/src/main/java/sorald/event/collectors/MinerStatisticsCollector.java
sorald/src/main/java/sorald/event/collectors/RepairStatisticsCollector.java
sorald/src/main/java/sorald/processor/XxeProcessingProcessor.java

Same reason as https://github.com/algomaster99/collector-sahab/pull/107.
The formatting change is due to an update.
> The basic form is always acceptable. The single-line form may be substituted when the entirety of the Javadoc block (including comment markers) can fit on a single line. Note that this only applies when there are no block tags such as @return. Source: https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line
The maven version is the CI is also 3.8.6 as confirmed [here](https://github.com/algomaster99/collector-sahab/pull/107/commits/6ce9beb3334f77a2017c2d3cede74e05e06f0e4b).

chore: update google-java-format to 1.15.0

---

sorald/pom.xml
sorald/src/test/resources-its/sorald/it/MineMojoIT/pom_configured/pom.xml

The maven plugin in previous release #910 did not work as expected because some of the dependencies were tagged to their `SNAPSHOTS` and that threw the following error.
```
[ERROR] Failed to execute goal se.kth.castor:sorald:0.7.0:mine (default-cli) on project gumtree-spoon-ast-diff: Execution default-cli of goal se.kth.castor:sorald:0.7.0:mine failed: Plugin se.kth.castor:sorald:0.7.0 or one of its dependencies could not be resolved: Failed to collect dependencies at se.kth.castor:sorald:jar:0.7.0 -> se.kth.castor:sorald-api:jar:0.0.2: Failed to read artifact descriptor for se.kth.castor:sorald-api:jar:0.0.2: Could not find artifact se.kth.castor:sorald-parent:pom:0.0.2-SNAPSHOT -> [Help 1]
```
#911 ensured that all versions are pinned so now I am releasing another version of `sorald` …

chore: release sorald 0.7.1

---

sorald/src/main/java/sorald/processor/UnusedPrivateFieldProcessor.java
sorald/src/test/resources/processor_test_files/S1068_UnusedPrivateField/PrivateFieldWrittenButNotRead.java
sorald/src/test/resources/processor_test_files/S1068_UnusedPrivateField/PrivateFieldWrittenButNotRead.java.expected

fix(S1068): delete field writes as well

---

sorald/src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.java
sorald/src/main/java/sorald/processor/CompareStringsBoxedTypesWithEqualsProcessor.md
sorald/src/test/resources/processor_test_files/S4973_CompareStringsBoxedTypesWithEquals/CompareStringsBoxedTypesWithEquals.java.expected

Fixes #915 
SonarSource has updated their [repair for S4973](https://rules.sonarsource.com/java/RSPEC-4973) and included a `null` check before comparison. Since we cannot know which operand is `null` while static analysing, we add a `null` check to the left operand.

fix(S4973): add null check to the overall expression

---

sorald/src/main/java/sorald/processor/UnusedPrivateFieldProcessor.java
sorald/src/test/resources/processor_test_files/S1068_UnusedPrivateField/PrivateFieldWrittenButNotRead.java
sorald/src/test/resources/processor_test_files/S1068_UnusedPrivateField/PrivateFieldWrittenButNotRead.java.expected

I forgot to add a filter to delete field writes of only those field which are unused in #917 . The changes ensure that all field writes are not deleted.

fix(S1068): delete field writes of violated field only

---

.github/workflows/deploy.yml

The `deploy` workflow was not doing anything for a while because it used to fetch the version of `sorald-parent` and that is fixed since https://github.com/SpoonLabs/sorald/pull/911 so the workflow used to skip deployment of `sorald` as well. Adding `-pl sorald` would compute the version of `sorald` module and not `sorald-parent`.

chore: fix sorald SNAPSHOT deployment

---

sorald/src/main/java/sorald/cli/MineCommand.java
sorald/src/main/java/sorald/cli/RepairCommand.java
sorald/src/main/java/sorald/cli/SoraldVersionProvider.java
sorald/src/test/java/sorald/cli/SoraldVersionProviderTest.java
sorald/src/test/java/sorald/miner/WarningMinerTest.java
sorald/src/test/resources/META-INF/bogus-manifests/MANIFEST-RELEASE-VERSION.MF
sorald/src/test/resources/META-INF/bogus-manifests/MANIFEST-SNAPSHOT-VERSION.MF
sorald/src/test/resources/META-INF/bogus-manifests/MANIFEST-WITHOUT-COMMIT-SHA.MF
sorald/src/test/resources/META-INF/bogus-manifests/MANIFEST-WITHOUT-VERSION.MF

Fixes #895 
The CLI always returned `LOCAL` and did not return the actual version. The changes fix that. Now, the SNAPSHOT versions return the `commit sha` and the releases return the version number.

fix: return correct version of sorald

---

sorald/src/test/resources-its/sorald/it/MineMojoIT/pom_configured/pom.xml

I removed the version tag from this test to avoid changing [it every time I release `sorald`](https://github.com/SpoonLabs/sorald/pull/927/files). One downside to this change is that we won't be testing this specific test with the latest SNAPSHOT, instead, we would be testing it with the latest release on maven central. I think it is a fine compromise to make because it is _very unlikely_ that other integration tests will pass, but this specific test will fail.
Initially, maven had an option `<version>LATEST</version>` to fetch the latest SNAPSHOT at build time and use it. However, it has been deprecated in maven `3.x` in favour of reproducibility.

tests: use latest release for pom_configured test

---

sorald/src/main/java/sorald/sonar/SonarLintEngine.java

This is causing some headaches as CI runs are failing without any clue as to *why*. The URL is reachable locally (but maybe not from the runner?) and the saving works (but maybe the runner has a permission or space issue?).
Was there a deliberate reason for swallowing the stacktrace here?

fix: Do not throw away stacktrace when downloading sonar java fails

---

.github/workflows/deploy.yml

The step [here](https://github.com/SpoonLabs/sorald/actions/runs/3959123404/jobs/6781537470#step:7:3027) indicates that the SNAPSHOT version of maven-plugin was not found. `mvn install`ing it should fix the issue.

chore: install the plugin locally before deploying

---

sorald/pom.xml
sorald/src/test/java/sorald/it/MineMojoIT.java
sorald/src/test/java/sorald/it/RepairMojoIT.java

Reference: https://github.com/SpoonLabs/sorald/pull/970 https://github.com/SpoonLabs/sorald/pull/971
This dependency upgrade caused [breaking changes](https://github.com/khmarbaise/maven-it-extension/blob/12d9354c7f75d7a17f82bac5ccbc70cc00e327d4/itf-documentation/src/main/asciidoc/release-notes/_release-notes-0.12.0.adoc) so needed to deal with them in a separate PR. @cesarsotovalero, you might require it too. Do take a look when you plan to upgrade it.

chore: update maven-plugin test extension

---

sorald/pom.xml
sorald/src/main/java/sorald/sonar/SonarLintEngine.java

Continues #954.
The extra fixes were needed to prevent the plugin instance loader from being closed.

chore: upgrade sonarlint-core to 8.14.0.63103

---

.github/workflows/tests.yml

Removing Sonar check because it is throwing `500` in our CI job - https://github.com/ASSERT-KTH/sorald/actions/runs/4819525681/jobs/8583103332?pr=1029.
I never really bothered to check it so maybe it is okay to remove it. I have the plugin locally installed so it informs me of the sonar violations. If Sonar is fixed soon, I will integrate this back.

ci: remove sonar check

---

sorald/src/main/java/sorald/processor/UnusedLocalVariableProcessor.java
sorald/src/main/java/sorald/processor/UnusedLocalVariableProcessor.md
sorald/src/test/resources/processor_test_files/S1481_UnusedLocalVariable/UnusedVariableInEnhancedForLoop.java
sorald/src/test/resources/processor_test_files/S1481_UnusedLocalVariable/UnusedVariableInEnhancedForLoop.java.expected

Fixes https://github.com/ASSERT-KTH/sorald/issues/1020
The issue has been there for quite some time. I had prepared a fix long ago, but SonarSource does not suggest it. I repaired the enhanced for-loop like so:
```diff
-        for (String input : inputList) { // noncompliant
+        for (int inputIterator=0; inputIterator < inputList.size(); ++inputIterator) { // compliant
doSomething();
}
```
For `Collection`, I use `.size`, and for arrays, I use `.length`.
I think this fix should be okay even though SonarSource does not suggest it. Do you have any opinions @Zuplyx and @khaes-kth against repairing something that SonarSource does not suggest?

fix(S1481): add repair for enhanced for-loop

---

.github/workflows/deploy.yml
.github/workflows/jreleaser.yml
.github/workflows/tests.yml
README.md
sorald/pom.xml

We used `-DskipUnitTests` and `-DskipIntegrationTests` for ci before these changes. I am reverting it back to use `-Dskip` which would act on both types of test. The advantage of it is following convention.

ci: use skipTests for skipping tests
